In [43]:
import pandas as pd
import numpy as np

import glob
import os
import os.path
import re
import sys
import warnings

from scipy.spatial import KDTree
from scipy.spatial import distance

from numpy.linalg import norm

#-------------------------------
from io import StringIO


import matplotlib.pyplot as plt
from matplotlib.cm import get_cmap, ScalarMappable
from matplotlib.patches import Rectangle
import matplotlib.colors as colors

#from mpl_toolkits.mplot3d import Axes3D

In [44]:
#def main():

# ignore warnings
warnings.filterwarnings("ignore")

In [45]:
bond_mean = df_bonds['angl'].mean()
bond_disp = df_bonds['angl'].std(ddof=1)

print(filename)
print(bond_mean, bond_disp)

cascades_form_spectra_for_movie_npt/results_bonds_data_vs_z_h2_shrinking/bonds_angl_data_h2_layer38.0_shrinking_final_pyro_cascades_simulation0.xyz
119.44249976441264 1.6197071598104356

In [46]:
def compute_angle_between_3d_points(a,b,c):
    ba = a - b
    bc = c - b

    cosine_numerator = np.sum(ba*bc, axis=1)
    cosine_denominator_1 = np.linalg.norm(ba, axis=1)
    cosine_denominator_2 = np.linalg.norm(bc, axis=1)
    cosine_angle = cosine_numerator / (cosine_denominator_1 * cosine_denominator_2)
    angles = np.arccos(cosine_angle)
    degree_angles = np.rad2deg(angles)

    return degree_angles

In [47]:
def layer_category_fix_n(zmin,zmax,n):
    layers_list = []
    beginning = zmin
    h_step = (zmax-zmin)/n
    n_layer = 0
    while (beginning < zmax):
        layers_list.append([beginning, beginning+h_step, h_step, n_layer])
        beginning = beginning + h_step 
        n_layer += 1
    return sorted(layers_list)

In [50]:
def bond_angle_calc_mean():
    
    # ignore warnings
    warnings.filterwarnings("ignore")
    
    #layer_height = int(sys.argv[-1])
    layer_height = 2
            
    #Creatte directory to put avg results
    directory_frames = f'cascades_form_spectra_for_movie_npt/results_bonds_data_vs_z_h{layer_height}_shrinking'
    directory = f'{directory_frames}/results_bonds_vs_z_h{layer_height}_shrinking'
    try:
        os.makedirs(directory)
    except FileExistsError:
        # directory already exists
        pass
    

    # list of all files
    list_files = glob.glob(f'{directory_frames}/bonds_angl_data_h2_layer*_shrinking_final_pyro_cascades_simulation*.xyz')
    #list_files = [list_files[0]]
    
    list_sim = []
    for filename in list_files:
        list_sim.append(re.search('simulation(.+?).xyz', filename).group(1))
        
    list_sim = list(set(list_sim))
    #list_sim = [list_sim[0]]
    print(list_sim)
        
    
    for simulation in list_sim:
        print(simulation)
        # load data from file
        filename = f"cascades_form_spectra_for_movie_npt/final_pyro_cascades_simulation{simulation}.xyz"
        input_data = open(filename).read()
        df_atoms = pd.read_table(filename, skiprows=9,
                                       names=['element', 'x', 'y', 'z', 'id', 'coord_num', 'pot_eng'],
                                       sep='\\s+')
        df_atoms = df_atoms.drop(['element'],axis=1)
            
                       
        # assign z_layer_fix_n
        init_intf = 6
        init_z_min = -169.64307163528616
        init_z_max = 150.98293179686004
        n = (init_z_max - init_z_min) //layer_height
            
        layers = layer_category_fix_n(df_atoms['z'].min(),df_atoms['z'].max(), n)        
        #print(layers)
        array=np.array(layers)        
        df_final = pd.DataFrame(array,columns=['beginning','ending','height','z_layers'])
        df_final['mean_bond_angl'] = 0
        df_final['disp_bond_angl'] = 0
        
         # list of files for certain simulation
        list_files = glob.glob(f'{directory_frames}/bonds_angl_data_h2_layer*_shrinking_final_pyro_cascades_simulation{simulation}.xyz')
        count_files = 1
        for filename in list_files:
            n = 73
            print(count_files, "/", len(list_files), "file name:", filename[n:])            
            layer = re.search('layer(.+?)_shrinking', filename).group(1)
        
            #load bond length data
            df_bonds = pd.read_table(filename, header=0, sep=',', index_col=0)
            
            a = df_bonds[['x_neigb1_atom','y_neigb1_atom','z_neigb1_atom']].to_numpy()
            b = df_bonds[['x_central_atom','y_central_atom','z_central_atom']].to_numpy()
            c = df_bonds[['x_neigb2_atom','y_neigb2_atom','z_neigb2_atom']].to_numpy()
            df_bonds['angl'] = compute_angle_between_3d_points(a,b,c)
            
            bond_mean = df_bonds['angl'].mean()
            bond_disp = df_bonds['angl'].std(ddof=1)
            
            df_final.loc[df_final['z_layers'] == float(layer), 'mean_bond_angl'] = bond_mean
            df_final.loc[df_final['z_layers'] == float(layer), 'disp_bond_angl'] = bond_disp
            print (layer, bond_mean, bond_disp)
            display(df_final[df_final['z_layers'] == float(layer)])
        
            count_files += 1
        
        border_factor = 0
        if border_factor == 0:
            file_angl = f'{directory}/bonds_angl_h{layer_height}_shrinking_final_pyro_cascades_simulation{simulation}.xyz'
        else:
            file_angl = f'{directory}/bonds_angl_h{layer_height}_b{border_factor}_shrinking_final_pyro_cascades_simulation{simulation}.xyz'
        
        
        df_final.to_csv(file_angl, sep=',')
        print("Done")

In [51]:
bond_angle_calc_mean()

['200', '350', '0', '500']
200
1 / 160 file name: bonds_angl_data_h2_layer115.0_shrinking_final_pyro_cascades_simulation200.xyz
115.0 115.78729756955934 8.3259526817057

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
115   80.74425  83.3178  2.57355     115.0      115.787298        8.325953

2 / 160 file name: bonds_angl_data_h2_layer148.0_shrinking_final_pyro_cascades_simulation200.xyz
148.0 115.60784691753257 8.577974691757888

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
148   165.6714  168.24495  2.57355     148.0      115.607847        8.577975

3 / 160 file name: bonds_angl_data_h2_layer133.0_shrinking_final_pyro_cascades_simulation200.xyz
133.0 116.01278688799648 8.002062894587633

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
133  127.06815  129.6417  2.57355     133.0      116.012787        8.002063

4 / 160 file name: bonds_angl_data_h2_layer99.0_shrinking_final_pyro_cascades_simulation200.xyz
99.0 116.34986843886126 7.733942569508676

    beginning  ending   height  z_layers  mean_bond_angl  disp_bond_angl
99   39.56745  42.141  2.57355      99.0      116.349868        7.733943

5 / 160 file name: bonds_angl_data_h2_layer126.0_shrinking_final_pyro_cascades_simulation200.xyz
126.0 116.41773426407272 7.676521781536441

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
126   109.0533  111.62685  2.57355     126.0      116.417734        7.676522

6 / 160 file name: bonds_angl_data_h2_layer54.0_shrinking_final_pyro_cascades_simulation200.xyz
54.0 118.61366248211672 4.3501566353428975

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
54   -76.2423 -73.66875  2.57355      54.0      118.613662        4.350157

7 / 160 file name: bonds_angl_data_h2_layer22.0_shrinking_final_pyro_cascades_simulation200.xyz
22.0 118.55848255823538 4.449565532128916

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
22  -158.5959 -156.02235  2.57355      22.0      118.558483        4.449566

8 / 160 file name: bonds_angl_data_h2_layer155.0_shrinking_final_pyro_cascades_simulation200.xyz
155.0 118.13949052697285 5.392681629390354

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
155  183.68625  186.2598  2.57355     155.0      118.139491        5.392682

9 / 160 file name: bonds_angl_data_h2_layer129.0_shrinking_final_pyro_cascades_simulation200.xyz
129.0 116.32856794243185 7.780305790019277

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
129  116.77395  119.3475  2.57355     129.0      116.328568        7.780306

10 / 160 file name: bonds_angl_data_h2_layer71.0_shrinking_final_pyro_cascades_simulation200.xyz
71.0 118.6298849923403 4.352859063358922

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
71  -32.49195 -29.9184  2.57355      71.0      118.629885        4.352859

11 / 160 file name: bonds_angl_data_h2_layer92.0_shrinking_final_pyro_cascades_simulation200.xyz
92.0 118.2150493143647 5.332494831870876

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
92    21.5526  24.12615  2.57355      92.0      118.215049        5.332495

12 / 160 file name: bonds_angl_data_h2_layer41.0_shrinking_final_pyro_cascades_simulation200.xyz
41.0 118.60217253848832 4.356300837206356

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
41 -109.69845 -107.1249  2.57355      41.0      118.602173        4.356301

13 / 160 file name: bonds_angl_data_h2_layer29.0_shrinking_final_pyro_cascades_simulation200.xyz
29.0 118.58482544935792 4.43591293598399

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
29 -140.58105 -138.0075  2.57355      29.0      118.584825        4.435913

14 / 160 file name: bonds_angl_data_h2_layer83.0_shrinking_final_pyro_cascades_simulation200.xyz
83.0 118.41473451947738 4.720613746499803

    beginning  ending   height  z_layers  mean_bond_angl  disp_bond_angl
83   -1.60935  0.9642  2.57355      83.0      118.414735        4.720614

15 / 160 file name: bonds_angl_data_h2_layer7.0_shrinking_final_pyro_cascades_simulation200.xyz
7.0 118.35987637504334 4.922448297032539

   beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
7 -197.19915 -194.6256  2.57355       7.0      118.359876        4.922448

16 / 160 file name: bonds_angl_data_h2_layer104.0_shrinking_final_pyro_cascades_simulation200.xyz
104.0 115.95961446509583 8.135642386988218

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
104    52.4352  55.00875  2.57355     104.0      115.959614        8.135642

17 / 160 file name: bonds_angl_data_h2_layer116.0_shrinking_final_pyro_cascades_simulation200.xyz
116.0 116.13249086178662 7.991191189369517

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
116    83.3178  85.89135  2.57355     116.0      116.132491        7.991191

18 / 160 file name: bonds_angl_data_h2_layer113.0_shrinking_final_pyro_cascades_simulation200.xyz
113.0 115.73697008491166 8.314384792874877

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
113   75.59715  78.1707  2.57355     113.0       115.73697        8.314385

19 / 160 file name: bonds_angl_data_h2_layer12.0_shrinking_final_pyro_cascades_simulation200.xyz
12.0 118.50689515833595 4.604354950207051

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
12  -184.3314 -181.75785  2.57355      12.0      118.506895        4.604355

20 / 160 file name: bonds_angl_data_h2_layer4.0_shrinking_final_pyro_cascades_simulation200.xyz
4.0 118.32106761999289 4.935769407627075

   beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
4  -204.9198 -202.34625  2.57355       4.0      118.321068        4.935769

21 / 160 file name: bonds_angl_data_h2_layer11.0_shrinking_final_pyro_cascades_simulation200.xyz
11.0 118.42585120876421 4.770150255224734

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
11 -186.90495 -184.3314  2.57355      11.0      118.425851         4.77015

22 / 160 file name: bonds_angl_data_h2_layer144.0_shrinking_final_pyro_cascades_simulation200.xyz
144.0 116.4366221868917 7.619931821341978

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
144   155.3772  157.95075  2.57355     144.0      116.436622        7.619932

23 / 160 file name: bonds_angl_data_h2_layer57.0_shrinking_final_pyro_cascades_simulation200.xyz
57.0 118.68082991581875 4.2100635741215

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
57  -68.52165 -65.9481  2.57355      57.0       118.68083        4.210064

24 / 160 file name: bonds_angl_data_h2_layer38.0_shrinking_final_pyro_cascades_simulation200.xyz
38.0 118.60477239315192 4.312525787394259

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
38  -117.4191 -114.84555  2.57355      38.0      118.604772        4.312526

25 / 160 file name: bonds_angl_data_h2_layer2.0_shrinking_final_pyro_cascades_simulation200.xyz
2.0 118.18526997926456 5.257817942330428

   beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
2  -210.0669 -207.49335  2.57355       2.0       118.18527        5.257818

26 / 160 file name: bonds_angl_data_h2_layer142.0_shrinking_final_pyro_cascades_simulation200.xyz
142.0 115.76477413248296 8.276462076602256

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
142   150.2301  152.80365  2.57355     142.0      115.764774        8.276462

27 / 160 file name: bonds_angl_data_h2_layer146.0_shrinking_final_pyro_cascades_simulation200.xyz
146.0 116.39710147722225 7.626563942696465

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
146   160.5243  163.09785  2.57355     146.0      116.397101        7.626564

28 / 160 file name: bonds_angl_data_h2_layer67.0_shrinking_final_pyro_cascades_simulation200.xyz
67.0 118.62984902157088 4.329688359838524

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
67  -42.78615 -40.2126  2.57355      67.0      118.629849        4.329688

29 / 160 file name: bonds_angl_data_h2_layer87.0_shrinking_final_pyro_cascades_simulation200.xyz
87.0 118.40460338987143 4.844309175177658

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
87    8.68485  11.2584  2.57355      87.0      118.404603        4.844309

30 / 160 file name: bonds_angl_data_h2_layer131.0_shrinking_final_pyro_cascades_simulation200.xyz
131.0 115.77748522387796 8.317877865413235

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
131  121.92105  124.4946  2.57355     131.0      115.777485        8.317878

31 / 160 file name: bonds_angl_data_h2_layer150.0_shrinking_final_pyro_cascades_simulation200.xyz
150.0 117.0810619026368 6.941481965001576

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
150   170.8185  173.39205  2.57355     150.0      117.081062        6.941482

32 / 160 file name: bonds_angl_data_h2_layer34.0_shrinking_final_pyro_cascades_simulation200.xyz
34.0 118.61004790770767 4.372311428595353

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
34  -127.7133 -125.13975  2.57355      34.0      118.610048        4.372311

33 / 160 file name: bonds_angl_data_h2_layer53.0_shrinking_final_pyro_cascades_simulation200.xyz
53.0 118.5897465342686 4.3575122124776

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
53  -78.81585 -76.2423  2.57355      53.0      118.589747        4.357512

34 / 160 file name: bonds_angl_data_h2_layer112.0_shrinking_final_pyro_cascades_simulation200.xyz
112.0 116.12368581286587 8.01356955530088

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
112    73.0236  75.59715  2.57355     112.0      116.123686         8.01357

35 / 160 file name: bonds_angl_data_h2_layer16.0_shrinking_final_pyro_cascades_simulation200.xyz
16.0 118.50327760043723 4.589653937125046

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
16  -174.0372 -171.46365  2.57355      16.0      118.503278        4.589654

36 / 160 file name: bonds_angl_data_h2_layer8.0_shrinking_final_pyro_cascades_simulation200.xyz
8.0 118.38955749904193 4.916099974322537

   beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
8  -194.6256 -192.05205  2.57355       8.0      118.389557          4.9161

37 / 160 file name: bonds_angl_data_h2_layer81.0_shrinking_final_pyro_cascades_simulation200.xyz
81.0 118.39523221142353 4.7909054847599375

    beginning  ending   height  z_layers  mean_bond_angl  disp_bond_angl
81   -6.75645 -4.1829  2.57355      81.0      118.395232        4.790905

38 / 160 file name: bonds_angl_data_h2_layer5.0_shrinking_final_pyro_cascades_simulation200.xyz
5.0 118.36919347984306 4.913943152149734

   beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
5 -202.34625 -199.7727  2.57355       5.0      118.369193        4.913943

39 / 160 file name: bonds_angl_data_h2_layer154.0_shrinking_final_pyro_cascades_simulation200.xyz
154.0 118.13279897293583 5.397471189771554

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
154   181.1127  183.68625  2.57355     154.0      118.132799        5.397471

40 / 160 file name: bonds_angl_data_h2_layer69.0_shrinking_final_pyro_cascades_simulation200.xyz
69.0 118.6467698126516 4.315880663393461

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
69  -37.63905 -35.0655  2.57355      69.0       118.64677        4.315881

41 / 160 file name: bonds_angl_data_h2_layer43.0_shrinking_final_pyro_cascades_simulation200.xyz
43.0 118.58775399063337 4.4463177643361105

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
43 -104.55135 -101.9778  2.57355      43.0      118.587754        4.446318

42 / 160 file name: bonds_angl_data_h2_layer65.0_shrinking_final_pyro_cascades_simulation200.xyz
65.0 118.66694077739982 4.276755451881429

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
65  -47.93325 -45.3597  2.57355      65.0      118.666941        4.276755

43 / 160 file name: bonds_angl_data_h2_layer59.0_shrinking_final_pyro_cascades_simulation200.xyz
59.0 118.661021384002 4.2332137825868585

    beginning  ending   height  z_layers  mean_bond_angl  disp_bond_angl
59  -63.37455 -60.801  2.57355      59.0      118.661021        4.233214

44 / 160 file name: bonds_angl_data_h2_layer80.0_shrinking_final_pyro_cascades_simulation200.xyz
80.0 118.4301675839696 4.782520598006349

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
80      -9.33 -6.75645  2.57355      80.0      118.430168        4.782521

45 / 160 file name: bonds_angl_data_h2_layer84.0_shrinking_final_pyro_cascades_simulation200.xyz
84.0 118.38300691657265 4.896767528535021

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
84     0.9642  3.53775  2.57355      84.0      118.383007        4.896768

46 / 160 file name: bonds_angl_data_h2_layer39.0_shrinking_final_pyro_cascades_simulation200.xyz
39.0 118.65227675048989 4.188532525523841

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
39 -114.84555 -112.272  2.57355      39.0      118.652277        4.188533

47 / 160 file name: bonds_angl_data_h2_layer58.0_shrinking_final_pyro_cascades_simulation200.xyz
58.0 118.6784529148884 4.171457455286829

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
58   -65.9481 -63.37455  2.57355      58.0      118.678453        4.171457

48 / 160 file name: bonds_angl_data_h2_layer10.0_shrinking_final_pyro_cascades_simulation200.xyz
10.0 118.40717425509568 4.795017701928344

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
10  -189.4785 -186.90495  2.57355      10.0      118.407174        4.795018

49 / 160 file name: bonds_angl_data_h2_layer76.0_shrinking_final_pyro_cascades_simulation200.xyz
76.0 118.52914904175469 4.511660013541817

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
76   -19.6242 -17.05065  2.57355      76.0      118.529149         4.51166

50 / 160 file name: bonds_angl_data_h2_layer159.0_shrinking_final_pyro_cascades_simulation200.xyz
159.0 100.13157918591706 33.79494304038588

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
159  193.98045  196.554  2.57355     159.0      100.131579       33.794943

51 / 160 file name: bonds_angl_data_h2_layer42.0_shrinking_final_pyro_cascades_simulation200.xyz
42.0 118.6016735885609 4.407832203230803

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
42  -107.1249 -104.55135  2.57355      42.0      118.601674        4.407832

52 / 160 file name: bonds_angl_data_h2_layer28.0_shrinking_final_pyro_cascades_simulation200.xyz
28.0 118.61738733618603 4.30264916191432

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
28  -143.1546 -140.58105  2.57355      28.0      118.617387        4.302649

53 / 160 file name: bonds_angl_data_h2_layer52.0_shrinking_final_pyro_cascades_simulation200.xyz
52.0 118.6121074565323 4.374241570767298

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
52   -81.3894 -78.81585  2.57355      52.0      118.612107        4.374242

54 / 160 file name: bonds_angl_data_h2_layer78.0_shrinking_final_pyro_cascades_simulation200.xyz
78.0 118.47133716887258 4.673232056831133

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
78   -14.4771 -11.90355  2.57355      78.0      118.471337        4.673232

55 / 160 file name: bonds_angl_data_h2_layer32.0_shrinking_final_pyro_cascades_simulation200.xyz
32.0 118.66028221467604 4.227250625744812

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
32  -132.8604 -130.28685  2.57355      32.0      118.660282        4.227251

56 / 160 file name: bonds_angl_data_h2_layer3.0_shrinking_final_pyro_cascades_simulation200.xyz
3.0 118.26453144615796 5.033751081683616

   beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
3 -207.49335 -204.9198  2.57355       3.0      118.264531        5.033751

57 / 160 file name: bonds_angl_data_h2_layer49.0_shrinking_final_pyro_cascades_simulation200.xyz
49.0 118.60699474436548 4.354540087057407

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
49  -89.11005 -86.5365  2.57355      49.0      118.606995         4.35454

58 / 160 file name: bonds_angl_data_h2_layer110.0_shrinking_final_pyro_cascades_simulation200.xyz
110.0 116.63740672904919 7.46290298049657

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
110    67.8765  70.45005  2.57355     110.0      116.637407        7.462903

59 / 160 file name: bonds_angl_data_h2_layer105.0_shrinking_final_pyro_cascades_simulation200.xyz
105.0 115.74049878489478 8.391786653787793

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
105   55.00875  57.5823  2.57355     105.0      115.740499        8.391787

60 / 160 file name: bonds_angl_data_h2_layer20.0_shrinking_final_pyro_cascades_simulation200.xyz
20.0 118.5795846053499 4.380678803485554

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
20   -163.743 -161.16945  2.57355      20.0      118.579585        4.380679

61 / 160 file name: bonds_angl_data_h2_layer111.0_shrinking_final_pyro_cascades_simulation200.xyz
111.0 116.53171435690975 7.494753122705991

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
111   70.45005  73.0236  2.57355     111.0      116.531714        7.494753

62 / 160 file name: bonds_angl_data_h2_layer108.0_shrinking_final_pyro_cascades_simulation200.xyz
108.0 116.2644054329996 7.816282749738614

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
108    62.7294  65.30295  2.57355     108.0      116.264405        7.816283

63 / 160 file name: bonds_angl_data_h2_layer119.0_shrinking_final_pyro_cascades_simulation200.xyz
119.0 116.51905457434323 7.50815902146969

     beginning  ending   height  z_layers  mean_bond_angl  disp_bond_angl
119   91.03845  93.612  2.57355     119.0      116.519055        7.508159

64 / 160 file name: bonds_angl_data_h2_layer63.0_shrinking_final_pyro_cascades_simulation200.xyz
63.0 118.70865636951281 4.072882467696962

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
63  -53.08035 -50.5068  2.57355      63.0      118.708656        4.072882

65 / 160 file name: bonds_angl_data_h2_layer79.0_shrinking_final_pyro_cascades_simulation200.xyz
79.0 118.4538594105561 4.678047957715495

    beginning  ending   height  z_layers  mean_bond_angl  disp_bond_angl
79  -11.90355   -9.33  2.57355      79.0      118.453859        4.678048

66 / 160 file name: bonds_angl_data_h2_layer50.0_shrinking_final_pyro_cascades_simulation200.xyz
50.0 118.67060088200962 4.215391071498784

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
50   -86.5365 -83.96295  2.57355      50.0      118.670601        4.215391

67 / 160 file name: bonds_angl_data_h2_layer137.0_shrinking_final_pyro_cascades_simulation200.xyz
137.0 116.33136680529344 7.7428367984793205

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
137  137.36235  139.9359  2.57355     137.0      116.331367        7.742837

68 / 160 file name: bonds_angl_data_h2_layer151.0_shrinking_final_pyro_cascades_simulation200.xyz
151.0 117.79098354935529 5.888678673467986

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
151  173.39205  175.9656  2.57355     151.0      117.790984        5.888679

69 / 160 file name: bonds_angl_data_h2_layer62.0_shrinking_final_pyro_cascades_simulation200.xyz
62.0 118.74067048460007 4.073969364868197

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
62   -55.6539 -53.08035  2.57355      62.0       118.74067        4.073969

70 / 160 file name: bonds_angl_data_h2_layer21.0_shrinking_final_pyro_cascades_simulation200.xyz
21.0 118.55993587425019 4.435007263005762

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
21 -161.16945 -158.5959  2.57355      21.0      118.559936        4.435007

71 / 160 file name: bonds_angl_data_h2_layer72.0_shrinking_final_pyro_cascades_simulation200.xyz
72.0 118.6393854347549 4.291662283687105

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
72   -29.9184 -27.34485  2.57355      72.0      118.639385        4.291662

72 / 160 file name: bonds_angl_data_h2_layer138.0_shrinking_final_pyro_cascades_simulation200.xyz
138.0 116.15346504765863 8.041576137621215

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
138   139.9359  142.50945  2.57355     138.0      116.153465        8.041576

73 / 160 file name: bonds_angl_data_h2_layer64.0_shrinking_final_pyro_cascades_simulation200.xyz
64.0 118.67740344451154 4.164841427079497

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
64   -50.5068 -47.93325  2.57355      64.0      118.677403        4.164841

74 / 160 file name: bonds_angl_data_h2_layer30.0_shrinking_final_pyro_cascades_simulation200.xyz
30.0 118.6045388480816 4.377412583693143

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
30  -138.0075 -135.43395  2.57355      30.0      118.604539        4.377413

75 / 160 file name: bonds_angl_data_h2_layer40.0_shrinking_final_pyro_cascades_simulation200.xyz
40.0 118.669512081062 4.197558786774668

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
40   -112.272 -109.69845  2.57355      40.0      118.669512        4.197559

76 / 160 file name: bonds_angl_data_h2_layer61.0_shrinking_final_pyro_cascades_simulation200.xyz
61.0 118.72743018277264 4.087343501886123

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
61  -58.22745 -55.6539  2.57355      61.0       118.72743        4.087344

77 / 160 file name: bonds_angl_data_h2_layer37.0_shrinking_final_pyro_cascades_simulation200.xyz
37.0 118.556808355844 4.521766349183812

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
37 -119.99265 -117.4191  2.57355      37.0      118.556808        4.521766

78 / 160 file name: bonds_angl_data_h2_layer89.0_shrinking_final_pyro_cascades_simulation200.xyz
89.0 118.27488268863777 5.179267021345058

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
89   13.83195  16.4055  2.57355      89.0      118.274883        5.179267

79 / 160 file name: bonds_angl_data_h2_layer156.0_shrinking_final_pyro_cascades_simulation200.xyz
156.0 118.24351438407923 5.129216423410358

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
156   186.2598  188.83335  2.57355     156.0      118.243514        5.129216

80 / 160 file name: bonds_angl_data_h2_layer114.0_shrinking_final_pyro_cascades_simulation200.xyz
114.0 115.5136002194454 8.57161950595161

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
114    78.1707  80.74425  2.57355     114.0        115.5136         8.57162

81 / 160 file name: bonds_angl_data_h2_layer143.0_shrinking_final_pyro_cascades_simulation200.xyz
143.0 116.13673743066954 8.0035628561386

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
143  152.80365  155.3772  2.57355     143.0      116.136737        8.003563

82 / 160 file name: bonds_angl_data_h2_layer128.0_shrinking_final_pyro_cascades_simulation200.xyz
128.0 116.5250087513969 7.4578674612993545

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
128   114.2004  116.77395  2.57355     128.0      116.525009        7.457867

83 / 160 file name: bonds_angl_data_h2_layer141.0_shrinking_final_pyro_cascades_simulation200.xyz
141.0 115.35843994924856 8.764608415536921

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
141  147.65655  150.2301  2.57355     141.0       115.35844        8.764608

84 / 160 file name: bonds_angl_data_h2_layer152.0_shrinking_final_pyro_cascades_simulation200.xyz
152.0 118.00721979248493 5.647246785598503

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
152   175.9656  178.53915  2.57355     152.0       118.00722        5.647247

85 / 160 file name: bonds_angl_data_h2_layer136.0_shrinking_final_pyro_cascades_simulation200.xyz
136.0 116.5457900741921 7.483626145313551

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
136   134.7888  137.36235  2.57355     136.0       116.54579        7.483626

86 / 160 file name: bonds_angl_data_h2_layer74.0_shrinking_final_pyro_cascades_simulation200.xyz
74.0 118.5573935405827 4.434473055619516

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
74   -24.7713 -22.19775  2.57355      74.0      118.557394        4.434473

87 / 160 file name: bonds_angl_data_h2_layer149.0_shrinking_final_pyro_cascades_simulation200.xyz
149.0 115.82544324497113 8.385327023798228

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
149  168.24495  170.8185  2.57355     149.0      115.825443        8.385327

88 / 160 file name: bonds_angl_data_h2_layer124.0_shrinking_final_pyro_cascades_simulation200.xyz
124.0 115.82007404711588 8.315951965734625

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
124   103.9062  106.47975  2.57355     124.0      115.820074        8.315952

89 / 160 file name: bonds_angl_data_h2_layer36.0_shrinking_final_pyro_cascades_simulation200.xyz
36.0 118.60087582586219 4.365237027888545

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
36  -122.5662 -119.99265  2.57355      36.0      118.600876        4.365237

90 / 160 file name: bonds_angl_data_h2_layer95.0_shrinking_final_pyro_cascades_simulation200.xyz
95.0 116.60592913176642 7.756920267418186

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
95   29.27325  31.8468  2.57355      95.0      116.605929         7.75692

91 / 160 file name: bonds_angl_data_h2_layer134.0_shrinking_final_pyro_cascades_simulation200.xyz
134.0 116.33739515838647 7.666562623276798

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
134   129.6417  132.21525  2.57355     134.0      116.337395        7.666563

92 / 160 file name: bonds_angl_data_h2_layer66.0_shrinking_final_pyro_cascades_simulation200.xyz
66.0 118.66544376750848 4.280228494427229

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
66   -45.3597 -42.78615  2.57355      66.0      118.665444        4.280228

93 / 160 file name: bonds_angl_data_h2_layer121.0_shrinking_final_pyro_cascades_simulation200.xyz
121.0 115.91738972244151 8.152268784751909

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
121   96.18555  98.7591  2.57355     121.0       115.91739        8.152269

94 / 160 file name: bonds_angl_data_h2_layer45.0_shrinking_final_pyro_cascades_simulation200.xyz
45.0 118.60445465039432 4.377836102543498

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
45  -99.40425 -96.8307  2.57355      45.0      118.604455        4.377836

95 / 160 file name: bonds_angl_data_h2_layer15.0_shrinking_final_pyro_cascades_simulation200.xyz
15.0 118.45780358333953 4.700336204386539

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
15 -176.61075 -174.0372  2.57355      15.0      118.457804        4.700336

96 / 160 file name: bonds_angl_data_h2_layer26.0_shrinking_final_pyro_cascades_simulation200.xyz
26.0 118.54533816555369 4.488786342379846

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
26  -148.3017 -145.72815  2.57355      26.0      118.545338        4.488786

97 / 160 file name: bonds_angl_data_h2_layer120.0_shrinking_final_pyro_cascades_simulation200.xyz
120.0 116.31448079558477 7.823976247359573

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
120     93.612  96.18555  2.57355     120.0      116.314481        7.823976

98 / 160 file name: bonds_angl_data_h2_layer117.0_shrinking_final_pyro_cascades_simulation200.xyz
117.0 116.34168621810205 7.766425120147107

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
117   85.89135  88.4649  2.57355     117.0      116.341686        7.766425

99 / 160 file name: bonds_angl_data_h2_layer158.0_shrinking_final_pyro_cascades_simulation200.xyz
158.0 101.7838324718136 32.89304683304803

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
158   191.4069  193.98045  2.57355     158.0      101.783832       32.893047

100 / 160 file name: bonds_angl_data_h2_layer122.0_shrinking_final_pyro_cascades_simulation200.xyz
122.0 115.49182036063293 8.653459741176691

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
122    98.7591  101.33265  2.57355     122.0       115.49182         8.65346

101 / 160 file name: bonds_angl_data_h2_layer93.0_shrinking_final_pyro_cascades_simulation200.xyz
93.0 118.1570376352753 5.331303767685981

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
93   24.12615  26.6997  2.57355      93.0      118.157038        5.331304

102 / 160 file name: bonds_angl_data_h2_layer75.0_shrinking_final_pyro_cascades_simulation200.xyz
75.0 118.50493511989252 4.560481481492776

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
75  -22.19775 -19.6242  2.57355      75.0      118.504935        4.560481

103 / 160 file name: bonds_angl_data_h2_layer55.0_shrinking_final_pyro_cascades_simulation200.xyz
55.0 118.59196276439891 4.4747259880270995

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
55  -73.66875 -71.0952  2.57355      55.0      118.591963        4.474726

104 / 160 file name: bonds_angl_data_h2_layer18.0_shrinking_final_pyro_cascades_simulation200.xyz
18.0 118.59092632498819 4.351420357226307

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
18  -168.8901 -166.31655  2.57355      18.0      118.590926         4.35142

105 / 160 file name: bonds_angl_data_h2_layer147.0_shrinking_final_pyro_cascades_simulation200.xyz
147.0 116.10399247058707 7.98143613737981

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
147  163.09785  165.6714  2.57355     147.0      116.103992        7.981436

106 / 160 file name: bonds_angl_data_h2_layer56.0_shrinking_final_pyro_cascades_simulation200.xyz
56.0 118.62721795167089 4.324752702414776

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
56   -71.0952 -68.52165  2.57355      56.0      118.627218        4.324753

107 / 160 file name: bonds_angl_data_h2_layer98.0_shrinking_final_pyro_cascades_simulation200.xyz
98.0 116.12962226330362 7.879161320021985

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
98    36.9939  39.56745  2.57355      98.0      116.129622        7.879161

108 / 160 file name: bonds_angl_data_h2_layer102.0_shrinking_final_pyro_cascades_simulation200.xyz
102.0 116.37238055542988 7.691453971194859

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
102    47.2881  49.86165  2.57355     102.0      116.372381        7.691454

109 / 160 file name: bonds_angl_data_h2_layer123.0_shrinking_final_pyro_cascades_simulation200.xyz
123.0 115.58883909275404 8.480860686637492

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
123  101.33265  103.9062  2.57355     123.0      115.588839        8.480861

110 / 160 file name: bonds_angl_data_h2_layer140.0_shrinking_final_pyro_cascades_simulation200.xyz
140.0 115.58762908858327 8.607634293144333

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
140    145.083  147.65655  2.57355     140.0      115.587629        8.607634

111 / 160 file name: bonds_angl_data_h2_layer77.0_shrinking_final_pyro_cascades_simulation200.xyz
77.0 118.49804756819286 4.639439381114786

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
77  -17.05065 -14.4771  2.57355      77.0      118.498048        4.639439

112 / 160 file name: bonds_angl_data_h2_layer51.0_shrinking_final_pyro_cascades_simulation200.xyz
51.0 118.64850594399017 4.289036992376217

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
51  -83.96295 -81.3894  2.57355      51.0      118.648506        4.289037

113 / 160 file name: bonds_angl_data_h2_layer27.0_shrinking_final_pyro_cascades_simulation200.xyz
27.0 118.57767880735432 4.40031990291973

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
27 -145.72815 -143.1546  2.57355      27.0      118.577679         4.40032

114 / 160 file name: bonds_angl_data_h2_layer135.0_shrinking_final_pyro_cascades_simulation200.xyz
135.0 116.5081063675994 7.501130550507904

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
135  132.21525  134.7888  2.57355     135.0      116.508106        7.501131

115 / 160 file name: bonds_angl_data_h2_layer25.0_shrinking_final_pyro_cascades_simulation200.xyz
25.0 118.51745634982574 4.622005942191333

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
25 -150.87525 -148.3017  2.57355      25.0      118.517456        4.622006

116 / 160 file name: bonds_angl_data_h2_layer70.0_shrinking_final_pyro_cascades_simulation200.xyz
70.0 118.66831895431217 4.287566584031773

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
70   -35.0655 -32.49195  2.57355      70.0      118.668319        4.287567

117 / 160 file name: bonds_angl_data_h2_layer33.0_shrinking_final_pyro_cascades_simulation200.xyz
33.0 118.62884150288072 4.273601428950306

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
33 -130.28685 -127.7133  2.57355      33.0      118.628842        4.273601

118 / 160 file name: bonds_angl_data_h2_layer139.0_shrinking_final_pyro_cascades_simulation200.xyz
139.0 115.97702186434377 8.130964074118053

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
139  142.50945  145.083  2.57355     139.0      115.977022        8.130964

119 / 160 file name: bonds_angl_data_h2_layer153.0_shrinking_final_pyro_cascades_simulation200.xyz
153.0 118.15873174345991 5.3369167762354115

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
153  178.53915  181.1127  2.57355     153.0      118.158732        5.336917

120 / 160 file name: bonds_angl_data_h2_layer103.0_shrinking_final_pyro_cascades_simulation200.xyz
103.0 116.16601768226087 7.908207570123343

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
103   49.86165  52.4352  2.57355     103.0      116.166018        7.908208

121 / 160 file name: bonds_angl_data_h2_layer106.0_shrinking_final_pyro_cascades_simulation200.xyz
106.0 115.61790792175951 8.511592699729794

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
106    57.5823  60.15585  2.57355     106.0      115.617908        8.511593

122 / 160 file name: bonds_angl_data_h2_layer60.0_shrinking_final_pyro_cascades_simulation200.xyz
60.0 118.69585004892221 4.091439956257515

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
60    -60.801 -58.22745  2.57355      60.0       118.69585         4.09144

123 / 160 file name: bonds_angl_data_h2_layer1.0_shrinking_final_pyro_cascades_simulation200.xyz
1.0 118.23404954116826 5.142421311857716

   beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
1 -212.64045 -210.0669  2.57355       1.0       118.23405        5.142421

124 / 160 file name: bonds_angl_data_h2_layer82.0_shrinking_final_pyro_cascades_simulation200.xyz
82.0 118.39553798712937 4.780557291300358

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
82    -4.1829 -1.60935  2.57355      82.0      118.395538        4.780557

125 / 160 file name: bonds_angl_data_h2_layer91.0_shrinking_final_pyro_cascades_simulation200.xyz
91.0 118.24272131478193 5.192065302025254

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
91   18.97905  21.5526  2.57355      91.0      118.242721        5.192065

126 / 160 file name: bonds_angl_data_h2_layer132.0_shrinking_final_pyro_cascades_simulation200.xyz
132.0 115.75605569813231 8.223013511307082

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
132   124.4946  127.06815  2.57355     132.0      115.756056        8.223014

127 / 160 file name: bonds_angl_data_h2_layer90.0_shrinking_final_pyro_cascades_simulation200.xyz
90.0 118.28794739720561 5.121393548986477

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
90    16.4055  18.97905  2.57355      90.0      118.287947        5.121394

128 / 160 file name: bonds_angl_data_h2_layer96.0_shrinking_final_pyro_cascades_simulation200.xyz
96.0 115.36960358689555 8.864551957885869

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
96    31.8468  34.42035  2.57355      96.0      115.369604        8.864552

129 / 160 file name: bonds_angl_data_h2_layer107.0_shrinking_final_pyro_cascades_simulation200.xyz
107.0 115.91229661610703 8.271088142284071

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
107   60.15585  62.7294  2.57355     107.0      115.912297        8.271088

130 / 160 file name: bonds_angl_data_h2_layer46.0_shrinking_final_pyro_cascades_simulation200.xyz
46.0 118.61342868235195 4.335688570968423

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
46   -96.8307 -94.25715  2.57355      46.0      118.613429        4.335689

131 / 160 file name: bonds_angl_data_h2_layer6.0_shrinking_final_pyro_cascades_simulation200.xyz
6.0 118.32827959670522 4.957951869957021

   beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
6  -199.7727 -197.19915  2.57355       6.0       118.32828        4.957952

132 / 160 file name: bonds_angl_data_h2_layer24.0_shrinking_final_pyro_cascades_simulation200.xyz
24.0 118.51098514439289 4.554537432842088

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
24  -153.4488 -150.87525  2.57355      24.0      118.510985        4.554537

133 / 160 file name: bonds_angl_data_h2_layer130.0_shrinking_final_pyro_cascades_simulation200.xyz
130.0 116.03705887693053 8.133024047674036

     beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
130   119.3475  121.92105  2.57355     130.0      116.037059        8.133024

134 / 160 file name: bonds_angl_data_h2_layer145.0_shrinking_final_pyro_cascades_simulation200.xyz
145.0 116.53822952892105 7.551275834044277

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
145  157.95075  160.5243  2.57355     145.0       116.53823        7.551276

135 / 160 file name: bonds_angl_data_h2_layer44.0_shrinking_final_pyro_cascades_simulation200.xyz
44.0 118.60474686272136 4.339558796906987

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
44  -101.9778 -99.40425  2.57355      44.0      118.604747        4.339559

136 / 160 file name: bonds_angl_data_h2_layer35.0_shrinking_final_pyro_cascades_simulation200.xyz
35.0 118.61497273036952 4.2896953391222254

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
35 -125.13975 -122.5662  2.57355      35.0      118.614973        4.289695

137 / 160 file name: bonds_angl_data_h2_layer0.0_shrinking_final_pyro_cascades_simulation200.xyz
0.0 118.29527544097535 5.0523332415058135

   beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
0   -215.214 -212.64045  2.57355       0.0      118.295275        5.052333

138 / 160 file name: bonds_angl_data_h2_layer125.0_shrinking_final_pyro_cascades_simulation200.xyz
125.0 116.13343698876004 7.94404161601831

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
125  106.47975  109.0533  2.57355     125.0      116.133437        7.944042

139 / 160 file name: bonds_angl_data_h2_layer23.0_shrinking_final_pyro_cascades_simulation200.xyz
23.0 118.4936888590049 4.595301110908793

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
23 -156.02235 -153.4488  2.57355      23.0      118.493689        4.595301

140 / 160 file name: bonds_angl_data_h2_layer101.0_shrinking_final_pyro_cascades_simulation200.xyz
101.0 116.48809172847673 7.495198888458367

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
101   44.71455  47.2881  2.57355     101.0      116.488092        7.495199

141 / 160 file name: bonds_angl_data_h2_layer118.0_shrinking_final_pyro_cascades_simulation200.xyz
118.0 116.48360730748554 7.594204825744066

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
118    88.4649  91.03845  2.57355     118.0      116.483607        7.594205

142 / 160 file name: bonds_angl_data_h2_layer100.0_shrinking_final_pyro_cascades_simulation200.xyz
100.0 116.42724508528057 7.637581476729177

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
100     42.141  44.71455  2.57355     100.0      116.427245        7.637581

143 / 160 file name: bonds_angl_data_h2_layer157.0_shrinking_final_pyro_cascades_simulation200.xyz
157.0 118.20259911152203 5.218058305818432

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
157  188.83335  191.4069  2.57355     157.0      118.202599        5.218058

144 / 160 file name: bonds_angl_data_h2_layer13.0_shrinking_final_pyro_cascades_simulation200.xyz
13.0 118.41911880377721 4.727307690072073

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
13 -181.75785 -179.1843  2.57355      13.0      118.419119        4.727308

145 / 160 file name: bonds_angl_data_h2_layer88.0_shrinking_final_pyro_cascades_simulation200.xyz
88.0 118.29687487615051 5.100061122690289

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
88    11.2584  13.83195  2.57355      88.0      118.296875        5.100061

146 / 160 file name: bonds_angl_data_h2_layer86.0_shrinking_final_pyro_cascades_simulation200.xyz
86.0 118.34810130143757 4.965930482287654

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
86     6.1113  8.68485  2.57355      86.0      118.348101         4.96593

147 / 160 file name: bonds_angl_data_h2_layer47.0_shrinking_final_pyro_cascades_simulation200.xyz
47.0 118.61891258516516 4.2891460050919505

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
47  -94.25715 -91.6836  2.57355      47.0      118.618913        4.289146

148 / 160 file name: bonds_angl_data_h2_layer19.0_shrinking_final_pyro_cascades_simulation200.xyz
19.0 118.59203736997048 4.388867311987217

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
19 -166.31655 -163.743  2.57355      19.0      118.592037        4.388867

149 / 160 file name: bonds_angl_data_h2_layer48.0_shrinking_final_pyro_cascades_simulation200.xyz
48.0 118.58579690323587 4.415105714154358

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
48   -91.6836 -89.11005  2.57355      48.0      118.585797        4.415106

150 / 160 file name: bonds_angl_data_h2_layer85.0_shrinking_final_pyro_cascades_simulation200.xyz
85.0 118.410194719652 4.814441809084349

    beginning  ending   height  z_layers  mean_bond_angl  disp_bond_angl
85    3.53775  6.1113  2.57355      85.0      118.410195        4.814442

151 / 160 file name: bonds_angl_data_h2_layer9.0_shrinking_final_pyro_cascades_simulation200.xyz
9.0 118.340233211851 4.994637174603473

   beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
9 -192.05205 -189.4785  2.57355       9.0      118.340233        4.994637

152 / 160 file name: bonds_angl_data_h2_layer31.0_shrinking_final_pyro_cascades_simulation200.xyz
31.0 118.63193190166629 4.330944081437603

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
31 -135.43395 -132.8604  2.57355      31.0      118.631932        4.330944

153 / 160 file name: bonds_angl_data_h2_layer17.0_shrinking_final_pyro_cascades_simulation200.xyz
17.0 118.59514052553055 4.403807585165068

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
17 -171.46365 -168.8901  2.57355      17.0      118.595141        4.403808

154 / 160 file name: bonds_angl_data_h2_layer109.0_shrinking_final_pyro_cascades_simulation200.xyz
109.0 116.54987758345601 7.4458285385843945

     beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
109   65.30295  67.8765  2.57355     109.0      116.549878        7.445829

155 / 160 file name: bonds_angl_data_h2_layer68.0_shrinking_final_pyro_cascades_simulation200.xyz
68.0 118.62428733290945 4.343798864558373

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
68   -40.2126 -37.63905  2.57355      68.0      118.624287        4.343799

156 / 160 file name: bonds_angl_data_h2_layer73.0_shrinking_final_pyro_cascades_simulation200.xyz
73.0 118.52736994937462 4.503626784316806

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
73  -27.34485 -24.7713  2.57355      73.0       118.52737        4.503627

157 / 160 file name: bonds_angl_data_h2_layer97.0_shrinking_final_pyro_cascades_simulation200.xyz
97.0 115.8025066084251 8.277790810640056

    beginning   ending   height  z_layers  mean_bond_angl  disp_bond_angl
97   34.42035  36.9939  2.57355      97.0      115.802507        8.277791

158 / 160 file name: bonds_angl_data_h2_layer94.0_shrinking_final_pyro_cascades_simulation200.xyz
94.0 117.85831359360007 5.968783459586002

    beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
94    26.6997  29.27325  2.57355      94.0      117.858314        5.968783

159 / 160 file name: bonds_angl_data_h2_layer14.0_shrinking_final_pyro_cascades_simulation200.xyz
14.0 118.43803188184162 4.709644385415848

    beginning     ending   height  z_layers  mean_bond_angl  disp_bond_angl
14  -179.1843 -176.61075  2.57355      14.0      118.438032        4.709644

160 / 160 file name: bonds_angl_data_h2_layer127.0_shrinking_final_pyro_cascades_simulation200.xyz
127.0 116.60788979554323 7.38086321115707

     beginning    ending   height  z_layers  mean_bond_angl  disp_bond_angl
127  111.62685  114.2004  2.57355     127.0       116.60789        7.380863

Done
350
1 / 161 file name: bonds_angl_data_h2_layer150.0_shrinking_final_pyro_cascades_simulation350.xyz
150.0 116.74650381024512 7.4864747817219595

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
150,173.283437,175.892194,2.608756,150.0,116.746504,7.486475

2 / 161 file name: bonds_angl_data_h2_layer16.0_shrinking_final_pyro_cascades_simulation350.xyz
16.0 117.75439849601572 5.990607030078626

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
16  -176.2899 -173.681144  2.608756      16.0      117.754398        5.990607

3 / 161 file name: bonds_angl_data_h2_layer2.0_shrinking_final_pyro_cascades_simulation350.xyz
2.0 117.49380494093343 6.366551945954427

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
2 -212.812488 -210.203731  2.608756       2.0      117.493805        6.366552

4 / 161 file name: bonds_angl_data_h2_layer157.0_shrinking_final_pyro_cascades_simulation350.xyz
157.0 117.32749691968905 6.6854006616912995

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
157,191.544731,194.153487,2.608756,157.0,117.327497,6.685401

5 / 161 file name: bonds_angl_data_h2_layer96.0_shrinking_final_pyro_cascades_simulation350.xyz
96.0 115.6342073045585 8.86536603475646

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
96    32.4106  35.019356  2.608756      96.0      115.634207        8.865366

6 / 161 file name: bonds_angl_data_h2_layer149.0_shrinking_final_pyro_cascades_simulation350.xyz
149.0 115.97426854624621 8.374083138303941

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
149,170.674681,173.283437,2.608756,149.0,115.974269,8.374083

7 / 161 file name: bonds_angl_data_h2_layer71.0_shrinking_final_pyro_cascades_simulation350.xyz
71.0 117.98560553359064 5.586687104141743

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
71 -32.808306 -30.19955  2.608756      71.0      117.985606        5.586687

8 / 161 file name: bonds_angl_data_h2_layer86.0_shrinking_final_pyro_cascades_simulation350.xyz
86.0 117.56605503249948 6.256232392653517

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
86   6.323037  8.931794  2.608756      86.0      117.566055        6.256232

9 / 161 file name: bonds_angl_data_h2_layer158.0_shrinking_final_pyro_cascades_simulation350.xyz
158.0 117.29791446094268 6.685049283094258

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
158,194.153487,196.762244,2.608756,158.0,117.297914,6.685049

10 / 161 file name: bonds_angl_data_h2_layer39.0_shrinking_final_pyro_cascades_simulation350.xyz
39.0 118.00623234008437 5.421464447761282

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
39 -116.288506 -113.67975  2.608756      39.0      118.006232        5.421464

11 / 161 file name: bonds_angl_data_h2_layer0.0_shrinking_final_pyro_cascades_simulation350.xyz
0.0 117.52820724232376 6.338141404714861

   beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
0    -218.03 -215.421244  2.608756       0.0      117.528207        6.338141

12 / 161 file name: bonds_angl_data_h2_layer32.0_shrinking_final_pyro_cascades_simulation350.xyz
32.0 117.98693447651829 5.508144593620393

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
32  -134.5498 -131.941044  2.608756      32.0      117.986934        5.508145

13 / 161 file name: bonds_angl_data_h2_layer66.0_shrinking_final_pyro_cascades_simulation350.xyz
66.0 118.00904196068645 5.44993426189903

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
66 -45.852088 -43.243331  2.608756      66.0      118.009042        5.449934

14 / 161 file name: bonds_angl_data_h2_layer61.0_shrinking_final_pyro_cascades_simulation350.xyz
61.0 117.9968628185805 5.5249882158362595

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
61 -58.895869 -56.287113  2.608756      61.0      117.996863        5.524988

15 / 161 file name: bonds_angl_data_h2_layer137.0_shrinking_final_pyro_cascades_simulation350.xyz
137.0 115.52704293946161 8.780054295561918

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
137,139.369606,141.978362,2.608756,137.0,115.527043,8.780054

16 / 161 file name: bonds_angl_data_h2_layer24.0_shrinking_final_pyro_cascades_simulation350.xyz
24.0 117.84520603537634 5.781917038148947

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
24 -155.41985 -152.811094  2.608756      24.0      117.845206        5.781917

17 / 161 file name: bonds_angl_data_h2_layer29.0_shrinking_final_pyro_cascades_simulation350.xyz
29.0 117.89827293318234 5.674123530227579

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
29 -142.376069 -139.767313  2.608756      29.0      117.898273        5.674124

18 / 161 file name: bonds_angl_data_h2_layer34.0_shrinking_final_pyro_cascades_simulation350.xyz
34.0 117.95591079907926 5.58949139136945

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
34 -129.332288 -126.723531  2.608756      34.0      117.955911        5.589491

19 / 161 file name: bonds_angl_data_h2_layer118.0_shrinking_final_pyro_cascades_simulation350.xyz
118.0 115.71350000773326 8.619427133591879

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
118  89.803237  92.411994  2.608756     118.0        115.7135        8.619427

20 / 161 file name: bonds_angl_data_h2_layer3.0_shrinking_final_pyro_cascades_simulation350.xyz
3.0 117.5357725311401 6.2591643074106456

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
3 -210.203731 -207.594975  2.608756       3.0      117.535773        6.259164

21 / 161 file name: bonds_angl_data_h2_layer20.0_shrinking_final_pyro_cascades_simulation350.xyz
20.0 117.74498647239788 5.9286963591904485

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
20 -165.854875 -163.246119  2.608756      20.0      117.744986        5.928696

22 / 161 file name: bonds_angl_data_h2_layer155.0_shrinking_final_pyro_cascades_simulation350.xyz
155.0 117.30849231830634 6.677397598887183

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
155,186.327219,188.935975,2.608756,155.0,117.308492,6.677398

23 / 161 file name: bonds_angl_data_h2_layer40.0_shrinking_final_pyro_cascades_simulation350.xyz
40.0 117.92847972866053 5.6348077726060595

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
40 -113.67975 -111.070994  2.608756      40.0       117.92848        5.634808

24 / 161 file name: bonds_angl_data_h2_layer69.0_shrinking_final_pyro_cascades_simulation350.xyz
69.0 117.97914563509995 5.590640353936337

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
69 -38.025819 -35.417063  2.608756      69.0      117.979146         5.59064

25 / 161 file name: bonds_angl_data_h2_layer6.0_shrinking_final_pyro_cascades_simulation350.xyz
6.0 117.52631963456705 6.3143433966073506

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
6 -202.377463 -199.768706  2.608756       6.0       117.52632        6.314343

26 / 161 file name: bonds_angl_data_h2_layer143.0_shrinking_final_pyro_cascades_simulation350.xyz
143.0 115.55577118091693 8.722130725333582

      beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
143  155.022144  157.6309  2.608756     143.0      115.555771        8.722131

27 / 161 file name: bonds_angl_data_h2_layer41.0_shrinking_final_pyro_cascades_simulation350.xyz
41.0 117.88275627262827 5.641447855087285

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
41 -111.070994 -108.462238  2.608756      41.0      117.882756        5.641448

28 / 161 file name: bonds_angl_data_h2_layer48.0_shrinking_final_pyro_cascades_simulation350.xyz
48.0 117.8642925883981 5.698902400941759

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
48   -92.8097 -90.200944  2.608756      48.0      117.864293        5.698902

29 / 161 file name: bonds_angl_data_h2_layer19.0_shrinking_final_pyro_cascades_simulation350.xyz
19.0 117.84834087499837 5.7510833427548445

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
19 -168.463631 -165.854875  2.608756      19.0      117.848341        5.751083

30 / 161 file name: bonds_angl_data_h2_layer94.0_shrinking_final_pyro_cascades_simulation350.xyz
94.0 117.15474324873945 7.020067912657304

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
94  27.193087  29.801844  2.608756      94.0      117.154743        7.020068

31 / 161 file name: bonds_angl_data_h2_layer72.0_shrinking_final_pyro_cascades_simulation350.xyz
72.0 117.9641432330147 5.593053592617581

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
72  -30.19955 -27.590794  2.608756      72.0      117.964143        5.593054

32 / 161 file name: bonds_angl_data_h2_layer9.0_shrinking_final_pyro_cascades_simulation350.xyz
9.0 117.68271031581754 6.044468957634272

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
9 -194.551194 -191.942438  2.608756       9.0       117.68271        6.044469

33 / 161 file name: bonds_angl_data_h2_layer8.0_shrinking_final_pyro_cascades_simulation350.xyz
8.0 117.62357368643191 6.19270646553279

   beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
8 -197.15995 -194.551194  2.608756       8.0      117.623574        6.192706

34 / 161 file name: bonds_angl_data_h2_layer22.0_shrinking_final_pyro_cascades_simulation350.xyz
22.0 117.75489384848996 5.894713823656484

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
22 -160.637363 -158.028606  2.608756      22.0      117.754894        5.894714

35 / 161 file name: bonds_angl_data_h2_layer88.0_shrinking_final_pyro_cascades_simulation350.xyz
88.0 117.52563202069285 6.380954204574695

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
88   11.54055  14.149306  2.608756      88.0      117.525632        6.380954

36 / 161 file name: bonds_angl_data_h2_layer146.0_shrinking_final_pyro_cascades_simulation350.xyz
146.0 115.42141685313774 8.905452300734977

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
146,162.848412,165.457169,2.608756,146.0,115.421417,8.905452

37 / 161 file name: bonds_angl_data_h2_layer141.0_shrinking_final_pyro_cascades_simulation350.xyz
141.0 114.9517110248405 9.301439612624952

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
141,149.804631,152.413387,2.608756,141.0,114.951711,9.30144

38 / 161 file name: bonds_angl_data_h2_layer25.0_shrinking_final_pyro_cascades_simulation350.xyz
25.0 117.80365797505459 5.784411513432433

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
25 -152.811094 -150.202338  2.608756      25.0      117.803658        5.784412

39 / 161 file name: bonds_angl_data_h2_layer95.0_shrinking_final_pyro_cascades_simulation350.xyz
95.0 116.88486514702453 7.415565511144023

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
95  29.801844  32.4106  2.608756      95.0      116.884865        7.415566

40 / 161 file name: bonds_angl_data_h2_layer50.0_shrinking_final_pyro_cascades_simulation350.xyz
50.0 117.92353961508476 5.595775597063262

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
50 -87.592188 -84.983431  2.608756      50.0       117.92354        5.595776

41 / 161 file name: bonds_angl_data_h2_layer12.0_shrinking_final_pyro_cascades_simulation350.xyz
12.0 117.65170793097472 6.136682577586703

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
12 -186.724925 -184.116169  2.608756      12.0      117.651708        6.136683

42 / 161 file name: bonds_angl_data_h2_layer10.0_shrinking_final_pyro_cascades_simulation350.xyz
10.0 117.70982648242449 5.9862759926128275

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
10 -191.942438 -189.333681  2.608756      10.0      117.709826        5.986276

43 / 161 file name: bonds_angl_data_h2_layer83.0_shrinking_final_pyro_cascades_simulation350.xyz
83.0 117.61033368923222 6.158782225577251

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
83  -1.503231  1.105525  2.608756      83.0      117.610334        6.158782

44 / 161 file name: bonds_angl_data_h2_layer46.0_shrinking_final_pyro_cascades_simulation350.xyz
46.0 117.91747650731688 5.557265763724496

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
46 -98.027213 -95.418456  2.608756      46.0      117.917477        5.557266

45 / 161 file name: bonds_angl_data_h2_layer129.0_shrinking_final_pyro_cascades_simulation350.xyz
129.0 115.54492454487894 8.750115340162955

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
129,118.499556,121.108312,2.608756,129.0,115.544925,8.750115

46 / 161 file name: bonds_angl_data_h2_layer101.0_shrinking_final_pyro_cascades_simulation350.xyz
101.0 115.80899417798193 8.403127739079874

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
101  45.454381  48.063137  2.608756     101.0      115.808994        8.403128

47 / 161 file name: bonds_angl_data_h2_layer111.0_shrinking_final_pyro_cascades_simulation350.xyz
111.0 115.77101309921976 8.49630910637983

     beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
111  71.541944  74.1507  2.608756     111.0      115.771013        8.496309

48 / 161 file name: bonds_angl_data_h2_layer47.0_shrinking_final_pyro_cascades_simulation350.xyz
47.0 117.90360008989359 5.598201944398916

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
47 -95.418456 -92.8097  2.608756      47.0        117.9036        5.598202

49 / 161 file name: bonds_angl_data_h2_layer55.0_shrinking_final_pyro_cascades_simulation350.xyz
55.0 117.92719327528238 5.619946296543268

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
55 -74.548406 -71.93965  2.608756      55.0      117.927193        5.619946

50 / 161 file name: bonds_angl_data_h2_layer136.0_shrinking_final_pyro_cascades_simulation350.xyz
136.0 115.74035153502071 8.578076324570425

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
136  136.76085  139.369606  2.608756     136.0      115.740352        8.578076

51 / 161 file name: bonds_angl_data_h2_layer43.0_shrinking_final_pyro_cascades_simulation350.xyz
43.0 117.88757788180239 5.712747187189498

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
43 -105.853481 -103.244725  2.608756      43.0      117.887578        5.712747

52 / 161 file name: bonds_angl_data_h2_layer27.0_shrinking_final_pyro_cascades_simulation350.xyz
27.0 117.88440970489899 5.676411266337353

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
27 -147.593581 -144.984825  2.608756      27.0       117.88441        5.676411

53 / 161 file name: bonds_angl_data_h2_layer133.0_shrinking_final_pyro_cascades_simulation350.xyz
133.0 115.41247185570748 8.812225215276024

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
133,128.934581,131.543337,2.608756,133.0,115.412472,8.812225

54 / 161 file name: bonds_angl_data_h2_layer127.0_shrinking_final_pyro_cascades_simulation350.xyz
127.0 115.82993530575597 8.406227072024162

      beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
127  113.282044  115.8908  2.608756     127.0      115.829935        8.406227

55 / 161 file name: bonds_angl_data_h2_layer54.0_shrinking_final_pyro_cascades_simulation350.xyz
54.0 117.86970005906967 5.643858984143323

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
54 -77.157163 -74.548406  2.608756      54.0        117.8697        5.643859

56 / 161 file name: bonds_angl_data_h2_layer62.0_shrinking_final_pyro_cascades_simulation350.xyz
62.0 118.06359224677205 5.332415346519527

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
62 -56.287113 -53.678356  2.608756      62.0      118.063592        5.332415

57 / 161 file name: bonds_angl_data_h2_layer63.0_shrinking_final_pyro_cascades_simulation350.xyz
63.0 118.0218657587852 5.496120783869152

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
63 -53.678356 -51.0696  2.608756      63.0      118.021866        5.496121

58 / 161 file name: bonds_angl_data_h2_layer7.0_shrinking_final_pyro_cascades_simulation350.xyz
7.0 117.59136598434957 6.2136279428346475

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
7 -199.768706 -197.15995  2.608756       7.0      117.591366        6.213628

59 / 161 file name: bonds_angl_data_h2_layer130.0_shrinking_final_pyro_cascades_simulation350.xyz
130.0 115.38912361529658 8.959339708469555

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
130,121.108312,123.717069,2.608756,130.0,115.389124,8.95934

60 / 161 file name: bonds_angl_data_h2_layer64.0_shrinking_final_pyro_cascades_simulation350.xyz
64.0 117.99969051471878 5.457920276901112

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
64   -51.0696 -48.460844  2.608756      64.0      117.999691         5.45792

61 / 161 file name: bonds_angl_data_h2_layer58.0_shrinking_final_pyro_cascades_simulation350.xyz
58.0 117.98756765869001 5.4583120777934795

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
58 -66.722138 -64.113381  2.608756      58.0      117.987568        5.458312

62 / 161 file name: bonds_angl_data_h2_layer103.0_shrinking_final_pyro_cascades_simulation350.xyz
103.0 115.56215594985694 8.664378858932544

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
103  50.671894  53.28065  2.608756     103.0      115.562156        8.664379

63 / 161 file name: bonds_angl_data_h2_layer99.0_shrinking_final_pyro_cascades_simulation350.xyz
99.0 115.67374370491743 8.520417016143174

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
99  40.236869  42.845625  2.608756      99.0      115.673744        8.520417

64 / 161 file name: bonds_angl_data_h2_layer1.0_shrinking_final_pyro_cascades_simulation350.xyz
1.0 117.42404025693311 6.539804911584233

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
1 -215.421244 -212.812488  2.608756       1.0       117.42404        6.539805

65 / 161 file name: bonds_angl_data_h2_layer152.0_shrinking_final_pyro_cascades_simulation350.xyz
152.0 117.268753215551 6.748436523548543

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
152  178.50095  181.109706  2.608756     152.0      117.268753        6.748437

66 / 161 file name: bonds_angl_data_h2_layer17.0_shrinking_final_pyro_cascades_simulation350.xyz
17.0 117.80179195411935 5.878515991154077

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
17 -173.681144 -171.072388  2.608756      17.0      117.801792        5.878516

67 / 161 file name: bonds_angl_data_h2_layer156.0_shrinking_final_pyro_cascades_simulation350.xyz
156.0 117.25844277617796 6.722424738570599

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
156,188.935975,191.544731,2.608756,156.0,117.258443,6.722425

68 / 161 file name: bonds_angl_data_h2_layer51.0_shrinking_final_pyro_cascades_simulation350.xyz
51.0 117.94022443969574 5.558195627078779

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
51 -84.983431 -82.374675  2.608756      51.0      117.940224        5.558196

69 / 161 file name: bonds_angl_data_h2_layer84.0_shrinking_final_pyro_cascades_simulation350.xyz
84.0 117.56835949208755 6.228680105609846

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
84   1.105525  3.714281  2.608756      84.0      117.568359         6.22868

70 / 161 file name: bonds_angl_data_h2_layer160.0_shrinking_final_pyro_cascades_simulation350.xyz
160.0 nan nan

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
160    199.371  201.979756  2.608756     160.0             NaN             NaN

71 / 161 file name: bonds_angl_data_h2_layer116.0_shrinking_final_pyro_cascades_simulation350.xyz
116.0 115.38077492671803 8.926644043261751

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
116  84.585725  87.194481  2.608756     116.0      115.380775        8.926644

72 / 161 file name: bonds_angl_data_h2_layer49.0_shrinking_final_pyro_cascades_simulation350.xyz
49.0 117.91111138765278 5.696154826625453

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
49 -90.200944 -87.592188  2.608756      49.0      117.911111        5.696155

73 / 161 file name: bonds_angl_data_h2_layer93.0_shrinking_final_pyro_cascades_simulation350.xyz
93.0 117.32004397520399 6.7419953453552575

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
93  24.584331  27.193087  2.608756      93.0      117.320044        6.741995

74 / 161 file name: bonds_angl_data_h2_layer59.0_shrinking_final_pyro_cascades_simulation350.xyz
59.0 118.00215717383186 5.426969006690528

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
59 -64.113381 -61.504625  2.608756      59.0      118.002157        5.426969

75 / 161 file name: bonds_angl_data_h2_layer121.0_shrinking_final_pyro_cascades_simulation350.xyz
121.0 115.24317046790705 9.11095449871064

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
121  97.629506  100.238262  2.608756     121.0       115.24317        9.110954

76 / 161 file name: bonds_angl_data_h2_layer5.0_shrinking_final_pyro_cascades_simulation350.xyz
5.0 117.56321499026319 6.258461953434548

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
5 -204.986219 -202.377463  2.608756       5.0      117.563215        6.258462

77 / 161 file name: bonds_angl_data_h2_layer98.0_shrinking_final_pyro_cascades_simulation350.xyz
98.0 115.34129992446252 8.828967101911642

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
98  37.628112  40.236869  2.608756      98.0        115.3413        8.828967

78 / 161 file name: bonds_angl_data_h2_layer79.0_shrinking_final_pyro_cascades_simulation350.xyz
79.0 117.73870451038114 5.93884848132338

    beginning  ending    height  z_layers  mean_bond_angl  disp_bond_angl
79 -11.938256 -9.3295  2.608756      79.0      117.738705        5.938848

79 / 161 file name: bonds_angl_data_h2_layer112.0_shrinking_final_pyro_cascades_simulation350.xyz
112.0 115.57712472556686 8.740956457750158

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
112    74.1507  76.759456  2.608756     112.0      115.577125        8.740956

80 / 161 file name: bonds_angl_data_h2_layer142.0_shrinking_final_pyro_cascades_simulation350.xyz
142.0 115.20393594272986 9.098341890078368

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
142,152.413387,155.022144,2.608756,142.0,115.203936,9.098342

81 / 161 file name: bonds_angl_data_h2_layer159.0_shrinking_final_pyro_cascades_simulation350.xyz
159.0 117.49630978512498 6.339882973195296

      beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
159  196.762244  199.371  2.608756     159.0       117.49631        6.339883

82 / 161 file name: bonds_angl_data_h2_layer131.0_shrinking_final_pyro_cascades_simulation350.xyz
131.0 115.090324821569 9.19426073473929

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
131,123.717069,126.325825,2.608756,131.0,115.090325,9.194261

83 / 161 file name: bonds_angl_data_h2_layer92.0_shrinking_final_pyro_cascades_simulation350.xyz
92.0 117.35599803158844 6.615900926277209

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
92  21.975575  24.584331  2.608756      92.0      117.355998        6.615901

84 / 161 file name: bonds_angl_data_h2_layer45.0_shrinking_final_pyro_cascades_simulation350.xyz
45.0 117.95805259998278 5.528390035479707

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
45 -100.635969 -98.027213  2.608756      45.0      117.958053         5.52839

85 / 161 file name: bonds_angl_data_h2_layer132.0_shrinking_final_pyro_cascades_simulation350.xyz
132.0 115.10836525669123 9.056220745295049

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
132,126.325825,128.934581,2.608756,132.0,115.108365,9.056221

86 / 161 file name: bonds_angl_data_h2_layer138.0_shrinking_final_pyro_cascades_simulation350.xyz
138.0 115.42632498772848 8.898967531576963

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
138,141.978362,144.587119,2.608756,138.0,115.426325,8.898968

87 / 161 file name: bonds_angl_data_h2_layer77.0_shrinking_final_pyro_cascades_simulation350.xyz
77.0 117.831696485967 5.793067609069645

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
77 -17.155769 -14.547013  2.608756      77.0      117.831696        5.793068

88 / 161 file name: bonds_angl_data_h2_layer124.0_shrinking_final_pyro_cascades_simulation350.xyz
124.0 115.06595953272151 9.232163429222407

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
124,105.455775,108.064531,2.608756,124.0,115.06596,9.232163

89 / 161 file name: bonds_angl_data_h2_layer80.0_shrinking_final_pyro_cascades_simulation350.xyz
80.0 117.66153592597372 6.103553172851586

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
80    -9.3295 -6.720744  2.608756      80.0      117.661536        6.103553

90 / 161 file name: bonds_angl_data_h2_layer78.0_shrinking_final_pyro_cascades_simulation350.xyz
78.0 117.78529822165949 5.944924055483475

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
78 -14.547013 -11.938256  2.608756      78.0      117.785298        5.944924

91 / 161 file name: bonds_angl_data_h2_layer87.0_shrinking_final_pyro_cascades_simulation350.xyz
87.0 117.50639101816714 6.396557755845298

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
87   8.931794  11.54055  2.608756      87.0      117.506391        6.396558

92 / 161 file name: bonds_angl_data_h2_layer106.0_shrinking_final_pyro_cascades_simulation350.xyz
106.0 115.05740705017476 9.184802715680679

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
106  58.498162  61.106919  2.608756     106.0      115.057407        9.184803

93 / 161 file name: bonds_angl_data_h2_layer97.0_shrinking_final_pyro_cascades_simulation350.xyz
97.0 114.92764284801123 9.30907719471004

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
97  35.019356  37.628112  2.608756      97.0      114.927643        9.309077

94 / 161 file name: bonds_angl_data_h2_layer151.0_shrinking_final_pyro_cascades_simulation350.xyz
151.0 117.01495618367674 7.217157811533641

      beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
151  175.892194  178.50095  2.608756     151.0      117.014956        7.217158

95 / 161 file name: bonds_angl_data_h2_layer81.0_shrinking_final_pyro_cascades_simulation350.xyz
81.0 117.61641585965528 6.1636485341954454

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
81  -6.720744 -4.111988  2.608756      81.0      117.616416        6.163649

96 / 161 file name: bonds_angl_data_h2_layer30.0_shrinking_final_pyro_cascades_simulation350.xyz
30.0 117.92794994739681 5.572591981644602

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
30 -139.767313 -137.158556  2.608756      30.0       117.92795        5.572592

97 / 161 file name: bonds_angl_data_h2_layer144.0_shrinking_final_pyro_cascades_simulation350.xyz
144.0 115.72816851188976 8.465837303571362

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
144   157.6309  160.239656  2.608756     144.0      115.728169        8.465837

98 / 161 file name: bonds_angl_data_h2_layer15.0_shrinking_final_pyro_cascades_simulation350.xyz
15.0 117.7136889694191 5.946163818527054

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
15 -178.898656 -176.2899  2.608756      15.0      117.713689        5.946164

99 / 161 file name: bonds_angl_data_h2_layer139.0_shrinking_final_pyro_cascades_simulation350.xyz
139.0 115.066770005563 9.320048964657271

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
139,144.587119,147.195875,2.608756,139.0,115.06677,9.320049

100 / 161 file name: bonds_angl_data_h2_layer126.0_shrinking_final_pyro_cascades_simulation350.xyz
126.0 115.70010062482994 8.600677605889391

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
126,110.673287,113.282044,2.608756,126.0,115.700101,8.600678

101 / 161 file name: bonds_angl_data_h2_layer100.0_shrinking_final_pyro_cascades_simulation350.xyz
100.0 115.75302552437061 8.455280252863126

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
100  42.845625  45.454381  2.608756     100.0      115.753026         8.45528

102 / 161 file name: bonds_angl_data_h2_layer134.0_shrinking_final_pyro_cascades_simulation350.xyz
134.0 115.70855303975313 8.573519693579307

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
134,131.543337,134.152094,2.608756,134.0,115.708553,8.57352

103 / 161 file name: bonds_angl_data_h2_layer74.0_shrinking_final_pyro_cascades_simulation350.xyz
74.0 117.87442161255964 5.7707401591975405

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
74 -24.982038 -22.373281  2.608756      74.0      117.874422         5.77074

104 / 161 file name: bonds_angl_data_h2_layer11.0_shrinking_final_pyro_cascades_simulation350.xyz
11.0 117.69436756281304 6.045744729281179

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
11 -189.333681 -186.724925  2.608756      11.0      117.694368        6.045745

105 / 161 file name: bonds_angl_data_h2_layer42.0_shrinking_final_pyro_cascades_simulation350.xyz
42.0 117.90571912772914 5.6603232548742275

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
42 -108.462238 -105.853481  2.608756      42.0      117.905719        5.660323

106 / 161 file name: bonds_angl_data_h2_layer135.0_shrinking_final_pyro_cascades_simulation350.xyz
135.0 115.82487717739468 8.416057831299973

      beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
135  134.152094  136.76085  2.608756     135.0      115.824877        8.416058

107 / 161 file name: bonds_angl_data_h2_layer85.0_shrinking_final_pyro_cascades_simulation350.xyz
85.0 117.56948013444035 6.235285535633285

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
85   3.714281  6.323037  2.608756      85.0       117.56948        6.235286

108 / 161 file name: bonds_angl_data_h2_layer18.0_shrinking_final_pyro_cascades_simulation350.xyz
18.0 117.82605215278038 5.7911488869192995

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
18 -171.072388 -168.463631  2.608756      18.0      117.826052        5.791149

109 / 161 file name: bonds_angl_data_h2_layer115.0_shrinking_final_pyro_cascades_simulation350.xyz
115.0 115.00403576614573 9.30634558472721

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
115  81.976969  84.585725  2.608756     115.0      115.004036        9.306346

110 / 161 file name: bonds_angl_data_h2_layer154.0_shrinking_final_pyro_cascades_simulation350.xyz
154.0 117.25375369092289 6.789805591658845

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
154,183.718462,186.327219,2.608756,154.0,117.253754,6.789806

111 / 161 file name: bonds_angl_data_h2_layer76.0_shrinking_final_pyro_cascades_simulation350.xyz
76.0 117.85621361470469 5.74974321190751

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
76 -19.764525 -17.155769  2.608756      76.0      117.856214        5.749743

112 / 161 file name: bonds_angl_data_h2_layer60.0_shrinking_final_pyro_cascades_simulation350.xyz
60.0 118.02653225091042 5.410198262772743

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
60 -61.504625 -58.895869  2.608756      60.0      118.026532        5.410198

113 / 161 file name: bonds_angl_data_h2_layer119.0_shrinking_final_pyro_cascades_simulation350.xyz
119.0 115.81215668757204 8.454228082745226

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
119  92.411994  95.02075  2.608756     119.0      115.812157        8.454228

114 / 161 file name: bonds_angl_data_h2_layer53.0_shrinking_final_pyro_cascades_simulation350.xyz
53.0 117.83682486887862 5.821314004219384

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
53 -79.765919 -77.157163  2.608756      53.0      117.836825        5.821314

115 / 161 file name: bonds_angl_data_h2_layer73.0_shrinking_final_pyro_cascades_simulation350.xyz
73.0 117.92823839911873 5.650488088798757

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
73 -27.590794 -24.982038  2.608756      73.0      117.928238        5.650488

116 / 161 file name: bonds_angl_data_h2_layer67.0_shrinking_final_pyro_cascades_simulation350.xyz
67.0 117.95040802856347 5.637456977112261

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
67 -43.243331 -40.634575  2.608756      67.0      117.950408        5.637457

117 / 161 file name: bonds_angl_data_h2_layer114.0_shrinking_final_pyro_cascades_simulation350.xyz
114.0 114.89798394461748 9.337325092989717

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
114  79.368212  81.976969  2.608756     114.0      114.897984        9.337325

118 / 161 file name: bonds_angl_data_h2_layer107.0_shrinking_final_pyro_cascades_simulation350.xyz
107.0 115.10084964395598 9.18286753840704

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
107  61.106919  63.715675  2.608756     107.0       115.10085        9.182868

119 / 161 file name: bonds_angl_data_h2_layer108.0_shrinking_final_pyro_cascades_simulation350.xyz
108.0 115.43369220854524 8.863927744027157

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
108  63.715675  66.324431  2.608756     108.0      115.433692        8.863928

120 / 161 file name: bonds_angl_data_h2_layer109.0_shrinking_final_pyro_cascades_simulation350.xyz
109.0 115.75196913513786 8.480023340654995

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
109  66.324431  68.933187  2.608756     109.0      115.751969        8.480023

121 / 161 file name: bonds_angl_data_h2_layer123.0_shrinking_final_pyro_cascades_simulation350.xyz
123.0 114.89196020801741 9.355850311651357

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
123,102.847019,105.455775,2.608756,123.0,114.89196,9.35585

122 / 161 file name: bonds_angl_data_h2_layer31.0_shrinking_final_pyro_cascades_simulation350.xyz
31.0 117.99918071508627 5.508809323181173

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
31 -137.158556 -134.5498  2.608756      31.0      117.999181        5.508809

123 / 161 file name: bonds_angl_data_h2_layer52.0_shrinking_final_pyro_cascades_simulation350.xyz
52.0 117.89133620483067 5.729214165866989

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
52 -82.374675 -79.765919  2.608756      52.0      117.891336        5.729214

124 / 161 file name: bonds_angl_data_h2_layer70.0_shrinking_final_pyro_cascades_simulation350.xyz
70.0 117.97005291884085 5.623329195664267

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
70 -35.417063 -32.808306  2.608756      70.0      117.970053        5.623329

125 / 161 file name: bonds_angl_data_h2_layer13.0_shrinking_final_pyro_cascades_simulation350.xyz
13.0 117.67974674348612 6.038220636492668

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
13 -184.116169 -181.507413  2.608756      13.0      117.679747        6.038221

126 / 161 file name: bonds_angl_data_h2_layer21.0_shrinking_final_pyro_cascades_simulation350.xyz
21.0 117.77212260878018 5.867742394514056

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
21 -163.246119 -160.637363  2.608756      21.0      117.772123        5.867742

127 / 161 file name: bonds_angl_data_h2_layer148.0_shrinking_final_pyro_cascades_simulation350.xyz
148.0 114.96882194641198 9.352687957676839

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
148,168.065925,170.674681,2.608756,148.0,114.968822,9.352688

128 / 161 file name: bonds_angl_data_h2_layer36.0_shrinking_final_pyro_cascades_simulation350.xyz
36.0 117.90739267575825 5.687009873693123

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
36 -124.114775 -121.506019  2.608756      36.0      117.907393         5.68701

129 / 161 file name: bonds_angl_data_h2_layer104.0_shrinking_final_pyro_cascades_simulation350.xyz
104.0 115.3959048191791 8.97109632180435

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
104   53.28065  55.889406  2.608756     104.0      115.395905        8.971096

130 / 161 file name: bonds_angl_data_h2_layer38.0_shrinking_final_pyro_cascades_simulation350.xyz
38.0 117.98814437405422 5.434641844133158

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
38 -118.897263 -116.288506  2.608756      38.0      117.988144        5.434642

131 / 161 file name: bonds_angl_data_h2_layer120.0_shrinking_final_pyro_cascades_simulation350.xyz
120.0 115.62642023857308 8.694333321384606

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
120   95.02075  97.629506  2.608756     120.0       115.62642        8.694333

132 / 161 file name: bonds_angl_data_h2_layer23.0_shrinking_final_pyro_cascades_simulation350.xyz
23.0 117.74370140432661 5.900304783892105

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
23 -158.028606 -155.41985  2.608756      23.0      117.743701        5.900305

133 / 161 file name: bonds_angl_data_h2_layer125.0_shrinking_final_pyro_cascades_simulation350.xyz
125.0 115.37013273991741 8.913521828833185

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
125,108.064531,110.673287,2.608756,125.0,115.370133,8.913522

134 / 161 file name: bonds_angl_data_h2_layer128.0_shrinking_final_pyro_cascades_simulation350.xyz
128.0 115.80455813657336 8.48669622399896

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
128   115.8908  118.499556  2.608756     128.0      115.804558        8.486696

135 / 161 file name: bonds_angl_data_h2_layer90.0_shrinking_final_pyro_cascades_simulation350.xyz
90.0 117.3878984839266 6.552035460608

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
90  16.758062  19.366819  2.608756      90.0      117.387898        6.552035

136 / 161 file name: bonds_angl_data_h2_layer33.0_shrinking_final_pyro_cascades_simulation350.xyz
33.0 117.9785315724362 5.54512101706947

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
33 -131.941044 -129.332288  2.608756      33.0      117.978532        5.545121

137 / 161 file name: bonds_angl_data_h2_layer26.0_shrinking_final_pyro_cascades_simulation350.xyz
26.0 117.8554546736947 5.798244269908052

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
26 -150.202338 -147.593581  2.608756      26.0      117.855455        5.798244

138 / 161 file name: bonds_angl_data_h2_layer89.0_shrinking_final_pyro_cascades_simulation350.xyz
89.0 117.47416024568112 6.41575803260934

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
89  14.149306  16.758062  2.608756      89.0       117.47416        6.415758

139 / 161 file name: bonds_angl_data_h2_layer140.0_shrinking_final_pyro_cascades_simulation350.xyz
140.0 114.78704233242267 9.43335115193322

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
140,147.195875,149.804631,2.608756,140.0,114.787042,9.433351

140 / 161 file name: bonds_angl_data_h2_layer57.0_shrinking_final_pyro_cascades_simulation350.xyz
57.0 117.92550156843089 5.672100137921732

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
57 -69.330894 -66.722138  2.608756      57.0      117.925502          5.6721

141 / 161 file name: bonds_angl_data_h2_layer35.0_shrinking_final_pyro_cascades_simulation350.xyz
35.0 117.95598847626366 5.572005049350416

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
35 -126.723531 -124.114775  2.608756      35.0      117.955988        5.572005

142 / 161 file name: bonds_angl_data_h2_layer105.0_shrinking_final_pyro_cascades_simulation350.xyz
105.0 115.20560897766778 9.073368785386311

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
105  55.889406  58.498162  2.608756     105.0      115.205609        9.073369

143 / 161 file name: bonds_angl_data_h2_layer65.0_shrinking_final_pyro_cascades_simulation350.xyz
65.0 118.06362918832883 5.343083391628327

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
65 -48.460844 -45.852088  2.608756      65.0      118.063629        5.343083

144 / 161 file name: bonds_angl_data_h2_layer153.0_shrinking_final_pyro_cascades_simulation350.xyz
153.0 117.20221254432882 6.864097766818947

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
153,181.109706,183.718462,2.608756,153.0,117.202213,6.864098

145 / 161 file name: bonds_angl_data_h2_layer56.0_shrinking_final_pyro_cascades_simulation350.xyz
56.0 118.01879127869537 5.47586942489633

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
56  -71.93965 -69.330894  2.608756      56.0      118.018791        5.475869

146 / 161 file name: bonds_angl_data_h2_layer82.0_shrinking_final_pyro_cascades_simulation350.xyz
82.0 117.61369837014679 6.150586502881938

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
82  -4.111988 -1.503231  2.608756      82.0      117.613698        6.150587

147 / 161 file name: bonds_angl_data_h2_layer44.0_shrinking_final_pyro_cascades_simulation350.xyz
44.0 117.95491265354245 5.597172940010045

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
44 -103.244725 -100.635969  2.608756      44.0      117.954913        5.597173

148 / 161 file name: bonds_angl_data_h2_layer147.0_shrinking_final_pyro_cascades_simulation350.xyz
147.0 115.07045251975134 9.31688675647901

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
147,165.457169,168.065925,2.608756,147.0,115.070453,9.316887

149 / 161 file name: bonds_angl_data_h2_layer28.0_shrinking_final_pyro_cascades_simulation350.xyz
28.0 117.86963498451544 5.700401872129132

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
28 -144.984825 -142.376069  2.608756      28.0      117.869635        5.700402

150 / 161 file name: bonds_angl_data_h2_layer91.0_shrinking_final_pyro_cascades_simulation350.xyz
91.0 117.3739434646708 6.640399758821871

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
91  19.366819  21.975575  2.608756      91.0      117.373943          6.6404

151 / 161 file name: bonds_angl_data_h2_layer14.0_shrinking_final_pyro_cascades_simulation350.xyz
14.0 117.66424439910266 6.146513662457798

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
14 -181.507413 -178.898656  2.608756      14.0      117.664244        6.146514

152 / 161 file name: bonds_angl_data_h2_layer122.0_shrinking_final_pyro_cascades_simulation350.xyz
122.0 114.92386701494283 9.398045025737112

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
122,100.238262,102.847019,2.608756,122.0,114.923867,9.398045

153 / 161 file name: bonds_angl_data_h2_layer113.0_shrinking_final_pyro_cascades_simulation350.xyz
113.0 115.19423995576129 9.059135750392349

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
113  76.759456  79.368212  2.608756     113.0       115.19424        9.059136

154 / 161 file name: bonds_angl_data_h2_layer145.0_shrinking_final_pyro_cascades_simulation350.xyz
145.0 115.67707994429817 8.612158652741002

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
145,160.239656,162.848412,2.608756,145.0,115.67708,8.612159

155 / 161 file name: bonds_angl_data_h2_layer68.0_shrinking_final_pyro_cascades_simulation350.xyz
68.0 117.96817850602467 5.569509781003363

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
68 -40.634575 -38.025819  2.608756      68.0      117.968179         5.56951

156 / 161 file name: bonds_angl_data_h2_layer117.0_shrinking_final_pyro_cascades_simulation350.xyz
117.0 115.56001910728658 8.763404655285877

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
117  87.194481  89.803237  2.608756     117.0      115.560019        8.763405

157 / 161 file name: bonds_angl_data_h2_layer4.0_shrinking_final_pyro_cascades_simulation350.xyz
4.0 117.55247410609677 6.283817197403378

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
4 -207.594975 -204.986219  2.608756       4.0      117.552474        6.283817

158 / 161 file name: bonds_angl_data_h2_layer37.0_shrinking_final_pyro_cascades_simulation350.xyz
37.0 117.87813934246138 5.682934488354618

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
37 -121.506019 -118.897263  2.608756      37.0      117.878139        5.682934

159 / 161 file name: bonds_angl_data_h2_layer110.0_shrinking_final_pyro_cascades_simulation350.xyz
110.0 115.84472006797239 8.449032536082637

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
110  68.933187  71.541944  2.608756     110.0       115.84472        8.449033

160 / 161 file name: bonds_angl_data_h2_layer102.0_shrinking_final_pyro_cascades_simulation350.xyz
102.0 115.76297106440083 8.443577031583262

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
102  48.063137  50.671894  2.608756     102.0      115.762971        8.443577

161 / 161 file name: bonds_angl_data_h2_layer75.0_shrinking_final_pyro_cascades_simulation350.xyz
75.0 117.81789342816877 5.771065994705478

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
75 -22.373281 -19.764525  2.608756      75.0      117.817893        5.771066

Done
0
1 / 160 file name: bonds_angl_data_h2_layer38.0_shrinking_final_pyro_cascades_simulation0.xyz
38.0 119.44249976441264 1.6197071598104356

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
38 -93.494325 -91.490412  2.003912      38.0        119.4425        1.619707

2 / 160 file name: bonds_angl_data_h2_layer76.0_shrinking_final_pyro_cascades_simulation0.xyz
76.0 119.44341026645753 1.5980350156944458

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
76  -17.34565 -15.341737  2.003912      76.0       119.44341        1.598035

3 / 160 file name: bonds_angl_data_h2_layer153.0_shrinking_final_pyro_cascades_simulation0.xyz
153.0 117.64291572016684 5.646814538599085

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
153,136.955613,138.959525,2.003912,153.0,117.642916,5.646815

4 / 160 file name: bonds_angl_data_h2_layer84.0_shrinking_final_pyro_cascades_simulation0.xyz
84.0 119.43198046795358 1.6360693282918863

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
84   -1.31435  0.689563  2.003912      84.0       119.43198        1.636069

5 / 160 file name: bonds_angl_data_h2_layer92.0_shrinking_final_pyro_cascades_simulation0.xyz
92.0 117.52520955958074 5.928025102664349

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
92   14.71695  16.720863  2.003912      92.0       117.52521        5.928025

6 / 160 file name: bonds_angl_data_h2_layer116.0_shrinking_final_pyro_cascades_simulation0.xyz
116.0 117.76227205515457 5.483181294613475

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
116   62.81085  64.814763  2.003912     116.0      117.762272        5.483181

7 / 160 file name: bonds_angl_data_h2_layer79.0_shrinking_final_pyro_cascades_simulation0.xyz
79.0 119.444931630708 1.6090222979222963

    beginning  ending    height  z_layers  mean_bond_angl  disp_bond_angl
79 -11.333912   -9.33  2.003912      79.0      119.444932        1.609022

8 / 160 file name: bonds_angl_data_h2_layer150.0_shrinking_final_pyro_cascades_simulation0.xyz
150.0 117.80559195673806 5.375545642404972

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
150,130.943875,132.947788,2.003912,150.0,117.805592,5.375546

9 / 160 file name: bonds_angl_data_h2_layer59.0_shrinking_final_pyro_cascades_simulation0.xyz
59.0 119.44651505859589 1.627847117325303

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
59 -51.412162 -49.40825  2.003912      59.0      119.446515        1.627847

10 / 160 file name: bonds_angl_data_h2_layer0.0_shrinking_final_pyro_cascades_simulation0.xyz
0.0 119.44137931223459 1.6034602140254288

   beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
0   -169.643 -167.639087  2.003912       0.0      119.441379         1.60346

11 / 160 file name: bonds_angl_data_h2_layer74.0_shrinking_final_pyro_cascades_simulation0.xyz
74.0 119.43691778802139 1.634765827972885

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
74 -21.353475 -19.349562  2.003912      74.0      119.436918        1.634766

12 / 160 file name: bonds_angl_data_h2_layer83.0_shrinking_final_pyro_cascades_simulation0.xyz
83.0 119.44405583242995 1.6012543347301906

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
83  -3.318262 -1.31435  2.003912      83.0      119.444056        1.601254

13 / 160 file name: bonds_angl_data_h2_layer148.0_shrinking_final_pyro_cascades_simulation0.xyz
148.0 117.14874193087104 6.345452130790106

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
148  126.93605  128.939963  2.003912     148.0      117.148742        6.345452

14 / 160 file name: bonds_angl_data_h2_layer126.0_shrinking_final_pyro_cascades_simulation0.xyz
126.0 117.58280613348668 5.702903010310082

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
126  82.849975  84.853888  2.003912     126.0      117.582806        5.702903

15 / 160 file name: bonds_angl_data_h2_layer58.0_shrinking_final_pyro_cascades_simulation0.xyz
58.0 119.4475066529798 1.5819750590024544

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
58 -53.416075 -51.412162  2.003912      58.0      119.447507        1.581975

16 / 160 file name: bonds_angl_data_h2_layer15.0_shrinking_final_pyro_cascades_simulation0.xyz
15.0 119.4421409596207 1.61673661100019

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
15 -139.584312 -137.5804  2.003912      15.0      119.442141        1.616737

17 / 160 file name: bonds_angl_data_h2_layer110.0_shrinking_final_pyro_cascades_simulation0.xyz
110.0 116.86337746598889 6.588954476303901

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
110  50.787375  52.791288  2.003912     110.0      116.863377        6.588954

18 / 160 file name: bonds_angl_data_h2_layer100.0_shrinking_final_pyro_cascades_simulation0.xyz
100.0 116.72716222268014 6.85008688427763

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
100   30.74825  32.752163  2.003912     100.0      116.727162        6.850087

19 / 160 file name: bonds_angl_data_h2_layer140.0_shrinking_final_pyro_cascades_simulation0.xyz
140.0 117.75221278958661 5.4860248381798

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
140  110.90475  112.908663  2.003912     140.0      117.752213        5.486025

20 / 160 file name: bonds_angl_data_h2_layer149.0_shrinking_final_pyro_cascades_simulation0.xyz
149.0 117.55143374186427 5.665447247972848

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
149,128.939963,130.943875,2.003912,149.0,117.551434,5.665447

21 / 160 file name: bonds_angl_data_h2_layer3.0_shrinking_final_pyro_cascades_simulation0.xyz
3.0 119.44244245799659 1.6360750919830926

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
3 -163.631262 -161.62735  2.003912       3.0      119.442442        1.636075

22 / 160 file name: bonds_angl_data_h2_layer97.0_shrinking_final_pyro_cascades_simulation0.xyz
97.0 117.37680897565448 6.073236914713099

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
97  24.736513  26.740425  2.003912      97.0      117.376809        6.073237

23 / 160 file name: bonds_angl_data_h2_layer136.0_shrinking_final_pyro_cascades_simulation0.xyz
136.0 117.22659873323762 6.094415221072755

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
136   102.8891  104.893013  2.003912     136.0      117.226599        6.094415

24 / 160 file name: bonds_angl_data_h2_layer66.0_shrinking_final_pyro_cascades_simulation0.xyz
66.0 119.4448490712928 1.595112720294207

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
66 -37.384775 -35.380862  2.003912      66.0      119.444849        1.595113

25 / 160 file name: bonds_angl_data_h2_layer146.0_shrinking_final_pyro_cascades_simulation0.xyz
146.0 116.48643748966259 7.16629863775752

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
146,122.928225,124.932138,2.003912,146.0,116.486437,7.166299

26 / 160 file name: bonds_angl_data_h2_layer56.0_shrinking_final_pyro_cascades_simulation0.xyz
56.0 119.45095549167283 1.5867255301620022

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
56   -57.4239 -55.419987  2.003912      56.0      119.450955        1.586726

27 / 160 file name: bonds_angl_data_h2_layer158.0_shrinking_final_pyro_cascades_simulation0.xyz
158.0 103.96111356084349 29.632254324068786

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
158,146.975175,148.979088,2.003912,158.0,103.961114,29.632254

28 / 160 file name: bonds_angl_data_h2_layer107.0_shrinking_final_pyro_cascades_simulation0.xyz
107.0 117.84854172231047 5.339720942475004

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
107  44.775638  46.77955  2.003912     107.0      117.848542        5.339721

29 / 160 file name: bonds_angl_data_h2_layer44.0_shrinking_final_pyro_cascades_simulation0.xyz
44.0 119.4460735314326 1.596465666026388

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
44  -81.47085 -79.466937  2.003912      44.0      119.446074        1.596466

30 / 160 file name: bonds_angl_data_h2_layer8.0_shrinking_final_pyro_cascades_simulation0.xyz
8.0 119.44469101871344 1.6335532467079275

   beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
8  -153.6117 -151.607787  2.003912       8.0      119.444691        1.633553

31 / 160 file name: bonds_angl_data_h2_layer13.0_shrinking_final_pyro_cascades_simulation0.xyz
13.0 119.44486247631507 1.6023050677718267

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
13 -143.592137 -141.588225  2.003912      13.0      119.444862        1.602305

32 / 160 file name: bonds_angl_data_h2_layer132.0_shrinking_final_pyro_cascades_simulation0.xyz
132.0 117.16838885543473 6.4602739254721975

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
132   94.87345  96.877363  2.003912     132.0      117.168389        6.460274

33 / 160 file name: bonds_angl_data_h2_layer129.0_shrinking_final_pyro_cascades_simulation0.xyz
129.0 117.83052322526423 5.368058178080771

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
129  88.861713  90.865625  2.003912     129.0      117.830523        5.368058

34 / 160 file name: bonds_angl_data_h2_layer16.0_shrinking_final_pyro_cascades_simulation0.xyz
16.0 119.44646424379314 1.6097629655998487

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
16  -137.5804 -135.576487  2.003912      16.0      119.446464        1.609763

35 / 160 file name: bonds_angl_data_h2_layer43.0_shrinking_final_pyro_cascades_simulation0.xyz
43.0 119.44114498127992 1.5759868309777232

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
43 -83.474762 -81.47085  2.003912      43.0      119.441145        1.575987

36 / 160 file name: bonds_angl_data_h2_layer86.0_shrinking_final_pyro_cascades_simulation0.xyz
86.0 118.88011506737882 3.775297926291057

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
86   2.693475  4.697388  2.003912      86.0      118.880115        3.775298

37 / 160 file name: bonds_angl_data_h2_layer23.0_shrinking_final_pyro_cascades_simulation0.xyz
23.0 119.44601403020847 1.6026026004806297

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
23 -123.553012 -121.5491  2.003912      23.0      119.446014        1.602603

38 / 160 file name: bonds_angl_data_h2_layer91.0_shrinking_final_pyro_cascades_simulation0.xyz
91.0 117.33193293009714 6.124669038102231

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
91  12.713038  14.71695  2.003912      91.0      117.331933        6.124669

39 / 160 file name: bonds_angl_data_h2_layer151.0_shrinking_final_pyro_cascades_simulation0.xyz
151.0 117.96989531093824 5.099557915395687

      beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
151  132.947788  134.9517  2.003912     151.0      117.969895        5.099558

40 / 160 file name: bonds_angl_data_h2_layer96.0_shrinking_final_pyro_cascades_simulation0.xyz
96.0 117.55040126644191 5.822460899479454

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
96    22.7326  24.736513  2.003912      96.0      117.550401        5.822461

41 / 160 file name: bonds_angl_data_h2_layer42.0_shrinking_final_pyro_cascades_simulation0.xyz
42.0 119.4451924315914 1.5978109992848089

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
42 -85.478675 -83.474762  2.003912      42.0      119.445192        1.597811

42 / 160 file name: bonds_angl_data_h2_layer55.0_shrinking_final_pyro_cascades_simulation0.xyz
55.0 119.45170334406293 1.5763855146272938

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
55 -59.427812 -57.4239  2.003912      55.0      119.451703        1.576386

43 / 160 file name: bonds_angl_data_h2_layer10.0_shrinking_final_pyro_cascades_simulation0.xyz
10.0 119.43917167182641 1.6283294889224662

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
10 -149.603875 -147.599962  2.003912      10.0      119.439172        1.628329

44 / 160 file name: bonds_angl_data_h2_layer5.0_shrinking_final_pyro_cascades_simulation0.xyz
5.0 119.44109565482725 1.626374766760749

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
5 -159.623437 -157.619525  2.003912       5.0      119.441096        1.626375

45 / 160 file name: bonds_angl_data_h2_layer51.0_shrinking_final_pyro_cascades_simulation0.xyz
51.0 119.4424678567063 1.6036708433406335

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
51 -67.443462 -65.43955  2.003912      51.0      119.442468        1.603671

46 / 160 file name: bonds_angl_data_h2_layer159.0_shrinking_final_pyro_cascades_simulation0.xyz
159.0 103.49426727260061 30.13208361747127

      beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
159  148.979088  150.983  2.003912     159.0      103.494267       30.132084

47 / 160 file name: bonds_angl_data_h2_layer53.0_shrinking_final_pyro_cascades_simulation0.xyz
53.0 119.4421750991731 1.605688533897152

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
53 -63.435637 -61.431725  2.003912      53.0      119.442175        1.605689

48 / 160 file name: bonds_angl_data_h2_layer1.0_shrinking_final_pyro_cascades_simulation0.xyz
1.0 119.43853610618396 1.6423873721945268

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
1 -167.639087 -165.635175  2.003912       1.0      119.438536        1.642387

49 / 160 file name: bonds_angl_data_h2_layer52.0_shrinking_final_pyro_cascades_simulation0.xyz
52.0 119.44488982769391 1.5963191645759836

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
52  -65.43955 -63.435637  2.003912      52.0       119.44489        1.596319

50 / 160 file name: bonds_angl_data_h2_layer137.0_shrinking_final_pyro_cascades_simulation0.xyz
137.0 117.43279124355324 5.864534241232989

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
137,104.893013,106.896925,2.003912,137.0,117.432791,5.864534

51 / 160 file name: bonds_angl_data_h2_layer9.0_shrinking_final_pyro_cascades_simulation0.xyz
9.0 119.4402535037832 1.6356237606027062

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
9 -151.607787 -149.603875  2.003912       9.0      119.440254        1.635624

52 / 160 file name: bonds_angl_data_h2_layer90.0_shrinking_final_pyro_cascades_simulation0.xyz
90.0 117.17254702879512 6.262234021008373

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
90  10.709125  12.713038  2.003912      90.0      117.172547        6.262234

53 / 160 file name: bonds_angl_data_h2_layer71.0_shrinking_final_pyro_cascades_simulation0.xyz
71.0 119.43963862880277 1.6160660908969815

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
71 -27.365212 -25.3613  2.003912      71.0      119.439639        1.616066

54 / 160 file name: bonds_angl_data_h2_layer14.0_shrinking_final_pyro_cascades_simulation0.xyz
14.0 119.44248161771876 1.6147849848445535

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
14 -141.588225 -139.584312  2.003912      14.0      119.442482        1.614785

55 / 160 file name: bonds_angl_data_h2_layer152.0_shrinking_final_pyro_cascades_simulation0.xyz
152.0 117.8555099226906 5.303732691460379

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
152   134.9517  136.955613  2.003912     152.0       117.85551        5.303733

56 / 160 file name: bonds_angl_data_h2_layer106.0_shrinking_final_pyro_cascades_simulation0.xyz
106.0 117.8163252988339 5.431024371276087

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
106  42.771725  44.775638  2.003912     106.0      117.816325        5.431024

57 / 160 file name: bonds_angl_data_h2_layer69.0_shrinking_final_pyro_cascades_simulation0.xyz
69.0 119.43661214850916 1.6285543885182245

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
69 -31.373037 -29.369125  2.003912      69.0      119.436612        1.628554

58 / 160 file name: bonds_angl_data_h2_layer112.0_shrinking_final_pyro_cascades_simulation0.xyz
112.0 116.91524967663973 6.660703818869163

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
112    54.7952  56.799113  2.003912     112.0       116.91525        6.660704

59 / 160 file name: bonds_angl_data_h2_layer121.0_shrinking_final_pyro_cascades_simulation0.xyz
121.0 116.83192806908347 6.6998488721917635

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
121  72.830413  74.834325  2.003912     121.0      116.831928        6.699849

60 / 160 file name: bonds_angl_data_h2_layer2.0_shrinking_final_pyro_cascades_simulation0.xyz
2.0 119.42683350775287 1.6606609859655859

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
2 -165.635175 -163.631262  2.003912       2.0      119.426834        1.660661

61 / 160 file name: bonds_angl_data_h2_layer40.0_shrinking_final_pyro_cascades_simulation0.xyz
40.0 119.44577827760678 1.5835153381286724

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
40   -89.4865 -87.482587  2.003912      40.0      119.445778        1.583515

62 / 160 file name: bonds_angl_data_h2_layer120.0_shrinking_final_pyro_cascades_simulation0.xyz
120.0 117.33386406871645 6.119825632251685

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
120    70.8265  72.830413  2.003912     120.0      117.333864        6.119826

63 / 160 file name: bonds_angl_data_h2_layer134.0_shrinking_final_pyro_cascades_simulation0.xyz
134.0 116.65071829463191 6.9098563427019535

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
134  98.881275  100.885188  2.003912     134.0      116.650718        6.909856

64 / 160 file name: bonds_angl_data_h2_layer49.0_shrinking_final_pyro_cascades_simulation0.xyz
49.0 119.44488088960603 1.6032941585597555

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
49 -71.451287 -69.447375  2.003912      49.0      119.444881        1.603294

65 / 160 file name: bonds_angl_data_h2_layer144.0_shrinking_final_pyro_cascades_simulation0.xyz
144.0 117.16055675948994 6.331294794145814

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
144   118.9204  120.924313  2.003912     144.0      117.160557        6.331295

66 / 160 file name: bonds_angl_data_h2_layer133.0_shrinking_final_pyro_cascades_simulation0.xyz
133.0 116.82666752757876 6.772447048589489

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
133  96.877363  98.881275  2.003912     133.0      116.826668        6.772447

67 / 160 file name: bonds_angl_data_h2_layer31.0_shrinking_final_pyro_cascades_simulation0.xyz
31.0 119.44980206531122 1.6006584763391254

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
31 -107.521712 -105.5178  2.003912      31.0      119.449802        1.600658

68 / 160 file name: bonds_angl_data_h2_layer155.0_shrinking_final_pyro_cascades_simulation0.xyz
155.0 116.86702166418884 6.786447960166936

      beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
155  140.963438  142.96735  2.003912     155.0      116.867022        6.786448

69 / 160 file name: bonds_angl_data_h2_layer98.0_shrinking_final_pyro_cascades_simulation0.xyz
98.0 117.19769137454114 6.293298331932807

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
98  26.740425  28.744338  2.003912      98.0      117.197691        6.293298

70 / 160 file name: bonds_angl_data_h2_layer99.0_shrinking_final_pyro_cascades_simulation0.xyz
99.0 116.93995423240003 6.625633247201308

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
99  28.744338  30.74825  2.003912      99.0      116.939954        6.625633

71 / 160 file name: bonds_angl_data_h2_layer39.0_shrinking_final_pyro_cascades_simulation0.xyz
39.0 119.43480498169706 1.6137081872449048

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
39 -91.490412 -89.4865  2.003912      39.0      119.434805        1.613708

72 / 160 file name: bonds_angl_data_h2_layer30.0_shrinking_final_pyro_cascades_simulation0.xyz
30.0 119.44891027964849 1.5850499829938118

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
30 -109.525625 -107.521712  2.003912      30.0       119.44891         1.58505

73 / 160 file name: bonds_angl_data_h2_layer143.0_shrinking_final_pyro_cascades_simulation0.xyz
143.0 117.42045156688205 6.06114546152714

      beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
143  116.916488  118.9204  2.003912     143.0      117.420452        6.061145

74 / 160 file name: bonds_angl_data_h2_layer18.0_shrinking_final_pyro_cascades_simulation0.xyz
18.0 119.44322655887585 1.6052499131706222

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
18 -133.572575 -131.568662  2.003912      18.0      119.443227         1.60525

75 / 160 file name: bonds_angl_data_h2_layer154.0_shrinking_final_pyro_cascades_simulation0.xyz
154.0 117.38210487001892 6.008867921276221

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
154,138.959525,140.963438,2.003912,154.0,117.382105,6.008868

76 / 160 file name: bonds_angl_data_h2_layer73.0_shrinking_final_pyro_cascades_simulation0.xyz
73.0 119.4449454099472 1.594540960854908

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
73 -23.357387 -21.353475  2.003912      73.0      119.444945        1.594541

77 / 160 file name: bonds_angl_data_h2_layer156.0_shrinking_final_pyro_cascades_simulation0.xyz
156.0 116.22384658166061 7.802532580180322

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
156  142.96735  144.971263  2.003912     156.0      116.223847        7.802533

78 / 160 file name: bonds_angl_data_h2_layer138.0_shrinking_final_pyro_cascades_simulation0.xyz
138.0 117.80702977522297 5.383840977553556

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
138,106.896925,108.900838,2.003912,138.0,117.80703,5.383841

79 / 160 file name: bonds_angl_data_h2_layer122.0_shrinking_final_pyro_cascades_simulation0.xyz
122.0 116.5861549676651 7.070592535835739

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
122  74.834325  76.838238  2.003912     122.0      116.586155        7.070593

80 / 160 file name: bonds_angl_data_h2_layer54.0_shrinking_final_pyro_cascades_simulation0.xyz
54.0 119.44347297250346 1.6033686155459117

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
54 -61.431725 -59.427812  2.003912      54.0      119.443473        1.603369

81 / 160 file name: bonds_angl_data_h2_layer102.0_shrinking_final_pyro_cascades_simulation0.xyz
102.0 117.10796830008718 6.505199348084513

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
102  34.756075  36.759988  2.003912     102.0      117.107968        6.505199

82 / 160 file name: bonds_angl_data_h2_layer142.0_shrinking_final_pyro_cascades_simulation0.xyz
142.0 117.48494427697122 5.882618181028701

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
142,114.912575,116.916488,2.003912,142.0,117.484944,5.882618

83 / 160 file name: bonds_angl_data_h2_layer7.0_shrinking_final_pyro_cascades_simulation0.xyz
7.0 119.43683859171664 1.6346414459014607

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
7 -155.615612 -153.6117  2.003912       7.0      119.436839        1.634641

84 / 160 file name: bonds_angl_data_h2_layer47.0_shrinking_final_pyro_cascades_simulation0.xyz
47.0 119.44878115536126 1.5637344874651367

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
47 -75.459112 -73.4552  2.003912      47.0      119.448781        1.563734

85 / 160 file name: bonds_angl_data_h2_layer119.0_shrinking_final_pyro_cascades_simulation0.xyz
119.0 117.52598071266553 5.950800596138002

     beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
119  68.822588  70.8265  2.003912     119.0      117.525981        5.950801

86 / 160 file name: bonds_angl_data_h2_layer6.0_shrinking_final_pyro_cascades_simulation0.xyz
6.0 119.44287780104506 1.6367074916140323

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
6 -157.619525 -155.615612  2.003912       6.0      119.442878        1.636707

87 / 160 file name: bonds_angl_data_h2_layer141.0_shrinking_final_pyro_cascades_simulation0.xyz
141.0 117.64946627496626 5.7348143577912545

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
141,112.908663,114.912575,2.003912,141.0,117.649466,5.734814

88 / 160 file name: bonds_angl_data_h2_layer26.0_shrinking_final_pyro_cascades_simulation0.xyz
26.0 119.4426396180107 1.6178572897362444

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
26 -117.541275 -115.537362  2.003912      26.0       119.44264        1.617857

89 / 160 file name: bonds_angl_data_h2_layer29.0_shrinking_final_pyro_cascades_simulation0.xyz
29.0 119.44800373138942 1.5923510111936077

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
29 -111.529537 -109.525625  2.003912      29.0      119.448004        1.592351

90 / 160 file name: bonds_angl_data_h2_layer24.0_shrinking_final_pyro_cascades_simulation0.xyz
24.0 119.43936536779093 1.6207978006229236

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
24  -121.5491 -119.545187  2.003912      24.0      119.439365        1.620798

91 / 160 file name: bonds_angl_data_h2_layer118.0_shrinking_final_pyro_cascades_simulation0.xyz
118.0 117.78390198603246 5.450115780405339

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
118  66.818675  68.822588  2.003912     118.0      117.783902        5.450116

92 / 160 file name: bonds_angl_data_h2_layer93.0_shrinking_final_pyro_cascades_simulation0.xyz
93.0 117.66229541211274 5.747171780013506

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
93  16.720863  18.724775  2.003912      93.0      117.662295        5.747172

93 / 160 file name: bonds_angl_data_h2_layer63.0_shrinking_final_pyro_cascades_simulation0.xyz
63.0 119.44333255125754 1.5879184457083002

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
63 -43.396512 -41.3926  2.003912      63.0      119.443333        1.587918

94 / 160 file name: bonds_angl_data_h2_layer82.0_shrinking_final_pyro_cascades_simulation0.xyz
82.0 119.43564055494697 1.6211373507543736

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
82  -5.322175 -3.318262  2.003912      82.0      119.435641        1.621137

95 / 160 file name: bonds_angl_data_h2_layer62.0_shrinking_final_pyro_cascades_simulation0.xyz
62.0 119.44341089338884 1.6167831786059914

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
62 -45.400425 -43.396512  2.003912      62.0      119.443411        1.616783

96 / 160 file name: bonds_angl_data_h2_layer17.0_shrinking_final_pyro_cascades_simulation0.xyz
17.0 119.44940536163084 1.5939346335760791

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
17 -135.576487 -133.572575  2.003912      17.0      119.449405        1.593935

97 / 160 file name: bonds_angl_data_h2_layer81.0_shrinking_final_pyro_cascades_simulation0.xyz
81.0 119.43854132033924 1.625216857930682

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
81  -7.326087 -5.322175  2.003912      81.0      119.438541        1.625217

98 / 160 file name: bonds_angl_data_h2_layer139.0_shrinking_final_pyro_cascades_simulation0.xyz
139.0 117.85006837432564 5.335766934885186

      beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
139  108.900838  110.90475  2.003912     139.0      117.850068        5.335767

99 / 160 file name: bonds_angl_data_h2_layer85.0_shrinking_final_pyro_cascades_simulation0.xyz
85.0 119.38685139318278 1.8859155207572862

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
85   0.689563  2.693475  2.003912      85.0      119.386851        1.885916

100 / 160 file name: bonds_angl_data_h2_layer80.0_shrinking_final_pyro_cascades_simulation0.xyz
80.0 119.43679188503725 1.6274468060894836

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
80      -9.33 -7.326087  2.003912      80.0      119.436792        1.627447

101 / 160 file name: bonds_angl_data_h2_layer101.0_shrinking_final_pyro_cascades_simulation0.xyz
101.0 116.63454161963446 6.918068073007857

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
101  32.752163  34.756075  2.003912     101.0      116.634542        6.918068

102 / 160 file name: bonds_angl_data_h2_layer127.0_shrinking_final_pyro_cascades_simulation0.xyz
127.0 117.72121467499277 5.536140815146696

     beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
127  84.853888  86.8578  2.003912     127.0      117.721215        5.536141

103 / 160 file name: bonds_angl_data_h2_layer22.0_shrinking_final_pyro_cascades_simulation0.xyz
22.0 119.44762306803455 1.5902737354418732

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
22 -125.556925 -123.553012  2.003912      22.0      119.447623        1.590274

104 / 160 file name: bonds_angl_data_h2_layer45.0_shrinking_final_pyro_cascades_simulation0.xyz
45.0 119.44261152265186 1.6205244837743178

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
45 -79.466937 -77.463025  2.003912      45.0      119.442612        1.620524

105 / 160 file name: bonds_angl_data_h2_layer37.0_shrinking_final_pyro_cascades_simulation0.xyz
37.0 119.44434324697853 1.6239154204310624

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
37 -95.498237 -93.494325  2.003912      37.0      119.444343        1.623915

106 / 160 file name: bonds_angl_data_h2_layer41.0_shrinking_final_pyro_cascades_simulation0.xyz
41.0 119.44787396412318 1.58850064781448

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
41 -87.482587 -85.478675  2.003912      41.0      119.447874        1.588501

107 / 160 file name: bonds_angl_data_h2_layer94.0_shrinking_final_pyro_cascades_simulation0.xyz
94.0 117.73757662021062 5.57055315952755

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
94  18.724775  20.728688  2.003912      94.0      117.737577        5.570553

108 / 160 file name: bonds_angl_data_h2_layer113.0_shrinking_final_pyro_cascades_simulation0.xyz
113.0 117.25955330193173 6.2041915127918505

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
113  56.799113  58.803025  2.003912     113.0      117.259553        6.204192

109 / 160 file name: bonds_angl_data_h2_layer103.0_shrinking_final_pyro_cascades_simulation0.xyz
103.0 117.44904683294696 6.042248280516163

     beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
103  36.759988  38.7639  2.003912     103.0      117.449047        6.042248

110 / 160 file name: bonds_angl_data_h2_layer27.0_shrinking_final_pyro_cascades_simulation0.xyz
27.0 119.44538178075928 1.5765127119762072

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
27 -115.537362 -113.53345  2.003912      27.0      119.445382        1.576513

111 / 160 file name: bonds_angl_data_h2_layer34.0_shrinking_final_pyro_cascades_simulation0.xyz
34.0 119.45124339841833 1.5850924191220557

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
34 -101.509975 -99.506062  2.003912      34.0      119.451243        1.585092

112 / 160 file name: bonds_angl_data_h2_layer36.0_shrinking_final_pyro_cascades_simulation0.xyz
36.0 119.45414551417963 1.5818350380557196

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
36  -97.50215 -95.498237  2.003912      36.0      119.454146        1.581835

113 / 160 file name: bonds_angl_data_h2_layer32.0_shrinking_final_pyro_cascades_simulation0.xyz
32.0 119.44445553443329 1.5928487716660424

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
32  -105.5178 -103.513887  2.003912      32.0      119.444456        1.592849

114 / 160 file name: bonds_angl_data_h2_layer20.0_shrinking_final_pyro_cascades_simulation0.xyz
20.0 119.44181262064399 1.5851396701282132

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
20 -129.56475 -127.560837  2.003912      20.0      119.441813         1.58514

115 / 160 file name: bonds_angl_data_h2_layer89.0_shrinking_final_pyro_cascades_simulation0.xyz
89.0 116.5763041786992 7.159768559839473

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
89   8.705213  10.709125  2.003912      89.0      116.576304        7.159769

116 / 160 file name: bonds_angl_data_h2_layer115.0_shrinking_final_pyro_cascades_simulation0.xyz
115.0 117.57298710528974 5.717685235067753

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
115  60.806938  62.81085  2.003912     115.0      117.572987        5.717685

117 / 160 file name: bonds_angl_data_h2_layer128.0_shrinking_final_pyro_cascades_simulation0.xyz
128.0 117.82534963987288 5.326841073766203

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
128    86.8578  88.861713  2.003912     128.0       117.82535        5.326841

118 / 160 file name: bonds_angl_data_h2_layer135.0_shrinking_final_pyro_cascades_simulation0.xyz
135.0 116.88161410189663 6.61079023505923

      beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
135  100.885188  102.8891  2.003912     135.0      116.881614         6.61079

119 / 160 file name: bonds_angl_data_h2_layer114.0_shrinking_final_pyro_cascades_simulation0.xyz
114.0 117.41415121478096 5.9875355485353605

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
114  58.803025  60.806938  2.003912     114.0      117.414151        5.987536

120 / 160 file name: bonds_angl_data_h2_layer65.0_shrinking_final_pyro_cascades_simulation0.xyz
65.0 119.44332108664275 1.587045456066066

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
65 -39.388687 -37.384775  2.003912      65.0      119.443321        1.587045

121 / 160 file name: bonds_angl_data_h2_layer12.0_shrinking_final_pyro_cascades_simulation0.xyz
12.0 119.4424531890341 1.6042123546945934

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
12 -145.59605 -143.592137  2.003912      12.0      119.442453        1.604212

122 / 160 file name: bonds_angl_data_h2_layer125.0_shrinking_final_pyro_cascades_simulation0.xyz
125.0 117.19296092696183 6.327472610210717

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
125  80.846063  82.849975  2.003912     125.0      117.192961        6.327473

123 / 160 file name: bonds_angl_data_h2_layer104.0_shrinking_final_pyro_cascades_simulation0.xyz
104.0 117.73564963665964 5.577590881094192

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
104    38.7639  40.767813  2.003912     104.0       117.73565        5.577591

124 / 160 file name: bonds_angl_data_h2_layer88.0_shrinking_final_pyro_cascades_simulation0.xyz
88.0 115.8025240073697 8.161282842385546

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
88     6.7013  8.705213  2.003912      88.0      115.802524        8.161283

125 / 160 file name: bonds_angl_data_h2_layer28.0_shrinking_final_pyro_cascades_simulation0.xyz
28.0 119.44610513187544 1.5904009123354326

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
28 -113.53345 -111.529537  2.003912      28.0      119.446105        1.590401

126 / 160 file name: bonds_angl_data_h2_layer145.0_shrinking_final_pyro_cascades_simulation0.xyz
145.0 116.71275346953998 6.781225088065647

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
145,120.924313,122.928225,2.003912,145.0,116.712753,6.781225

127 / 160 file name: bonds_angl_data_h2_layer35.0_shrinking_final_pyro_cascades_simulation0.xyz
35.0 119.45076296346835 1.5832572040780246

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
35 -99.506062 -97.50215  2.003912      35.0      119.450763        1.583257

128 / 160 file name: bonds_angl_data_h2_layer108.0_shrinking_final_pyro_cascades_simulation0.xyz
108.0 117.58598114022473 5.814771277551574

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
108   46.77955  48.783463  2.003912     108.0      117.585981        5.814771

129 / 160 file name: bonds_angl_data_h2_layer117.0_shrinking_final_pyro_cascades_simulation0.xyz
117.0 117.83780822305239 5.4421949960815725

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
117  64.814763  66.818675  2.003912     117.0      117.837808        5.442195

130 / 160 file name: bonds_angl_data_h2_layer111.0_shrinking_final_pyro_cascades_simulation0.xyz
111.0 116.5969360691705 7.085837499166771

     beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
111  52.791288  54.7952  2.003912     111.0      116.596936        7.085837

131 / 160 file name: bonds_angl_data_h2_layer95.0_shrinking_final_pyro_cascades_simulation0.xyz
95.0 117.66125857354898 5.696398090609763

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
95  20.728688  22.7326  2.003912      95.0      117.661259        5.696398

132 / 160 file name: bonds_angl_data_h2_layer67.0_shrinking_final_pyro_cascades_simulation0.xyz
67.0 119.44785851219908 1.5995020745536643

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
67 -35.380862 -33.37695  2.003912      67.0      119.447859        1.599502

133 / 160 file name: bonds_angl_data_h2_layer4.0_shrinking_final_pyro_cascades_simulation0.xyz
4.0 119.4462901381739 1.6255505541888569

   beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
4 -161.62735 -159.623437  2.003912       4.0       119.44629        1.625551

134 / 160 file name: bonds_angl_data_h2_layer105.0_shrinking_final_pyro_cascades_simulation0.xyz
105.0 117.93615347467734 5.237794246999453

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
105  40.767813  42.771725  2.003912     105.0      117.936153        5.237794

135 / 160 file name: bonds_angl_data_h2_layer147.0_shrinking_final_pyro_cascades_simulation0.xyz
147.0 116.66571461090727 6.912511038697825

      beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
147  124.932138  126.93605  2.003912     147.0      116.665715        6.912511

136 / 160 file name: bonds_angl_data_h2_layer21.0_shrinking_final_pyro_cascades_simulation0.xyz
21.0 119.44167974033316 1.5947662086401038

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
21 -127.560837 -125.556925  2.003912      21.0       119.44168        1.594766

137 / 160 file name: bonds_angl_data_h2_layer75.0_shrinking_final_pyro_cascades_simulation0.xyz
75.0 119.4458119571786 1.637146108752698

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
75 -19.349562 -17.34565  2.003912      75.0      119.445812        1.637146

138 / 160 file name: bonds_angl_data_h2_layer46.0_shrinking_final_pyro_cascades_simulation0.xyz
46.0 119.4412458148424 1.5960656108764353

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
46 -77.463025 -75.459112  2.003912      46.0      119.441246        1.596066

139 / 160 file name: bonds_angl_data_h2_layer77.0_shrinking_final_pyro_cascades_simulation0.xyz
77.0 119.44435803977692 1.6094269025597538

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
77 -15.341737 -13.337825  2.003912      77.0      119.444358        1.609427

140 / 160 file name: bonds_angl_data_h2_layer19.0_shrinking_final_pyro_cascades_simulation0.xyz
19.0 119.44655247976779 1.6168700278194943

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
19 -131.568662 -129.56475  2.003912      19.0      119.446552         1.61687

141 / 160 file name: bonds_angl_data_h2_layer11.0_shrinking_final_pyro_cascades_simulation0.xyz
11.0 119.44486087929178 1.608696727099802

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
11 -147.599962 -145.59605  2.003912      11.0      119.444861        1.608697

142 / 160 file name: bonds_angl_data_h2_layer157.0_shrinking_final_pyro_cascades_simulation0.xyz
157.0 117.19419887638777 6.642997443847534

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
157,144.971263,146.975175,2.003912,157.0,117.194199,6.642997

143 / 160 file name: bonds_angl_data_h2_layer70.0_shrinking_final_pyro_cascades_simulation0.xyz
70.0 119.43933428640382 1.626380558603316

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
70 -29.369125 -27.365212  2.003912      70.0      119.439334        1.626381

144 / 160 file name: bonds_angl_data_h2_layer57.0_shrinking_final_pyro_cascades_simulation0.xyz
57.0 119.44619663772826 1.6050886928847004

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
57 -55.419987 -53.416075  2.003912      57.0      119.446197        1.605089

145 / 160 file name: bonds_angl_data_h2_layer131.0_shrinking_final_pyro_cascades_simulation0.xyz
131.0 117.50451894026831 5.868841589394858

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
131  92.869538  94.87345  2.003912     131.0      117.504519        5.868842

146 / 160 file name: bonds_angl_data_h2_layer33.0_shrinking_final_pyro_cascades_simulation0.xyz
33.0 119.44493500957533 1.5978242576338113

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
33 -103.513887 -101.509975  2.003912      33.0      119.444935        1.597824

147 / 160 file name: bonds_angl_data_h2_layer78.0_shrinking_final_pyro_cascades_simulation0.xyz
78.0 119.43994989780731 1.6118987710872459

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
78 -13.337825 -11.333912  2.003912      78.0       119.43995        1.611899

148 / 160 file name: bonds_angl_data_h2_layer130.0_shrinking_final_pyro_cascades_simulation0.xyz
130.0 117.77368781423417 5.483511011679452

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
130  90.865625  92.869538  2.003912     130.0      117.773688        5.483511

149 / 160 file name: bonds_angl_data_h2_layer109.0_shrinking_final_pyro_cascades_simulation0.xyz
109.0 117.22386771124192 6.25741199729765

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
109  48.783463  50.787375  2.003912     109.0      117.223868        6.257412

150 / 160 file name: bonds_angl_data_h2_layer72.0_shrinking_final_pyro_cascades_simulation0.xyz
72.0 119.44766322046523 1.601370343003536

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
72   -25.3613 -23.357387  2.003912      72.0      119.447663         1.60137

151 / 160 file name: bonds_angl_data_h2_layer124.0_shrinking_final_pyro_cascades_simulation0.xyz
124.0 117.0710770997929 6.387545437198697

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
124   78.84215  80.846063  2.003912     124.0      117.071077        6.387545

152 / 160 file name: bonds_angl_data_h2_layer68.0_shrinking_final_pyro_cascades_simulation0.xyz
68.0 119.44420333367485 1.6123217711507989

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
68  -33.37695 -31.373037  2.003912      68.0      119.444203        1.612322

153 / 160 file name: bonds_angl_data_h2_layer123.0_shrinking_final_pyro_cascades_simulation0.xyz
123.0 116.74305916505074 6.83207478276907

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
123  76.838238  78.84215  2.003912     123.0      116.743059        6.832075

154 / 160 file name: bonds_angl_data_h2_layer60.0_shrinking_final_pyro_cascades_simulation0.xyz
60.0 119.44034161826295 1.6094381160571585

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
60  -49.40825 -47.404337  2.003912      60.0      119.440342        1.609438

155 / 160 file name: bonds_angl_data_h2_layer64.0_shrinking_final_pyro_cascades_simulation0.xyz
64.0 119.45069369419181 1.5966861410198743

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
64   -41.3926 -39.388687  2.003912      64.0      119.450694        1.596686

156 / 160 file name: bonds_angl_data_h2_layer25.0_shrinking_final_pyro_cascades_simulation0.xyz
25.0 119.44513679344657 1.6089941351882693

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
25 -119.545187 -117.541275  2.003912      25.0      119.445137        1.608994

157 / 160 file name: bonds_angl_data_h2_layer87.0_shrinking_final_pyro_cascades_simulation0.xyz
87.0 117.02330682825577 7.1745479787676

    beginning  ending    height  z_layers  mean_bond_angl  disp_bond_angl
87   4.697388  6.7013  2.003912      87.0      117.023307        7.174548

158 / 160 file name: bonds_angl_data_h2_layer61.0_shrinking_final_pyro_cascades_simulation0.xyz
61.0 119.44976066087156 1.6040737670691338

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
61 -47.404337 -45.400425  2.003912      61.0      119.449761        1.604074

159 / 160 file name: bonds_angl_data_h2_layer50.0_shrinking_final_pyro_cascades_simulation0.xyz
50.0 119.44369791171182 1.6036740693130258

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
50 -69.447375 -67.443462  2.003912      50.0      119.443698        1.603674

160 / 160 file name: bonds_angl_data_h2_layer48.0_shrinking_final_pyro_cascades_simulation0.xyz
48.0 119.43998325812717 1.6202127906237036

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
48   -73.4552 -71.451287  2.003912      48.0      119.439983        1.620213

Done
500
1 / 160 file name: bonds_angl_data_h2_layer149.0_shrinking_final_pyro_cascades_simulation500.xyz
149.0 115.574896785957 8.82152569658582

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
149,170.099256,172.699688,2.600431,149.0,115.574897,8.821526

2 / 160 file name: bonds_angl_data_h2_layer135.0_shrinking_final_pyro_cascades_simulation500.xyz
135.0 115.1907754544275 9.15100647376797

      beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
135  133.693219  136.29365  2.600431     135.0      115.190775        9.151006

3 / 160 file name: bonds_angl_data_h2_layer13.0_shrinking_final_pyro_cascades_simulation500.xyz
13.0 117.00552884318489 7.036896424796236

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
13 -183.559394 -180.958962  2.600431      13.0      117.005529        7.036896

4 / 160 file name: bonds_angl_data_h2_layer45.0_shrinking_final_pyro_cascades_simulation500.xyz
45.0 117.33698070041194 6.462789536253105

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
45 -100.345594 -97.745162  2.600431      45.0      117.336981         6.46279

5 / 160 file name: bonds_angl_data_h2_layer90.0_shrinking_final_pyro_cascades_simulation500.xyz
90.0 116.68394925085857 7.572352386999059

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
90  16.673813  19.274244  2.600431      90.0      116.683949        7.572352

6 / 160 file name: bonds_angl_data_h2_layer30.0_shrinking_final_pyro_cascades_simulation500.xyz
30.0 117.3914873566131 6.415534241512436

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
30 -139.352062 -136.751631  2.600431      30.0      117.391487        6.415534

7 / 160 file name: bonds_angl_data_h2_layer145.0_shrinking_final_pyro_cascades_simulation500.xyz
145.0 115.03691185660945 9.318983922123868

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
145,159.697531,162.297963,2.600431,145.0,115.036912,9.318984

8 / 160 file name: bonds_angl_data_h2_layer86.0_shrinking_final_pyro_cascades_simulation500.xyz
86.0 116.76656530168057 7.441261520322761

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
86   6.272088  8.872519  2.600431      86.0      116.766565        7.441262

9 / 160 file name: bonds_angl_data_h2_layer139.0_shrinking_final_pyro_cascades_simulation500.xyz
139.0 114.54901219786639 9.90028556996437

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
139,144.094944,146.695375,2.600431,139.0,114.549012,9.900286

10 / 160 file name: bonds_angl_data_h2_layer142.0_shrinking_final_pyro_cascades_simulation500.xyz
142.0 114.74721716639704 9.634923821643035

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
142,151.896238,154.496669,2.600431,142.0,114.747217,9.634924

11 / 160 file name: bonds_angl_data_h2_layer46.0_shrinking_final_pyro_cascades_simulation500.xyz
46.0 117.33580507630919 6.487860508609539

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
46 -97.745162 -95.144731  2.600431      46.0      117.335805        6.487861

12 / 160 file name: bonds_angl_data_h2_layer44.0_shrinking_final_pyro_cascades_simulation500.xyz
44.0 117.27280072747679 6.58822573059699

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
44 -102.946025 -100.345594  2.600431      44.0      117.272801        6.588226

13 / 160 file name: bonds_angl_data_h2_layer157.0_shrinking_final_pyro_cascades_simulation500.xyz
157.0 116.59822627034973 7.697105297722716

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
157,190.902706,193.503138,2.600431,157.0,116.598226,7.697105

14 / 160 file name: bonds_angl_data_h2_layer131.0_shrinking_final_pyro_cascades_simulation500.xyz
131.0 114.55939463849565 9.788783094444023

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
131,123.291494,125.891925,2.600431,131.0,114.559395,9.788783

15 / 160 file name: bonds_angl_data_h2_layer115.0_shrinking_final_pyro_cascades_simulation500.xyz
115.0 114.43474987925246 9.90686419982721

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
115  81.684594  84.285025  2.600431     115.0       114.43475        9.906864

16 / 160 file name: bonds_angl_data_h2_layer7.0_shrinking_final_pyro_cascades_simulation500.xyz
7.0 116.89244880954375 7.2083230828388745

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
7 -199.161981 -196.56155  2.600431       7.0      116.892449        7.208323

17 / 160 file name: bonds_angl_data_h2_layer69.0_shrinking_final_pyro_cascades_simulation500.xyz
69.0 117.39485572246356 6.498430141311375

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
69 -37.935244 -35.334812  2.600431      69.0      117.394856         6.49843

18 / 160 file name: bonds_angl_data_h2_layer91.0_shrinking_final_pyro_cascades_simulation500.xyz
91.0 116.59738049282687 7.686656305426165

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
91  19.274244  21.874675  2.600431      91.0       116.59738        7.686656

19 / 160 file name: bonds_angl_data_h2_layer63.0_shrinking_final_pyro_cascades_simulation500.xyz
63.0 117.47405692265919 6.313635442592593

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
63 -53.537831 -50.9374  2.600431      63.0      117.474057        6.313635

20 / 160 file name: bonds_angl_data_h2_layer56.0_shrinking_final_pyro_cascades_simulation500.xyz
56.0 117.40497540691582 6.4814616024501985

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
56  -71.74085 -69.140419  2.600431      56.0      117.404975        6.481462

21 / 160 file name: bonds_angl_data_h2_layer96.0_shrinking_final_pyro_cascades_simulation500.xyz
96.0 115.55250511210792 8.910481640733943

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
96    32.2764  34.876831  2.600431      96.0      115.552505        8.910482

22 / 160 file name: bonds_angl_data_h2_layer10.0_shrinking_final_pyro_cascades_simulation500.xyz
10.0 117.06020304175874 6.9467801356823164

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
10 -191.360687 -188.760256  2.600431      10.0      117.060203         6.94678

23 / 160 file name: bonds_angl_data_h2_layer31.0_shrinking_final_pyro_cascades_simulation500.xyz
31.0 117.36104282239758 6.590875844344046

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
31 -136.751631 -134.1512  2.600431      31.0      117.361043        6.590876

24 / 160 file name: bonds_angl_data_h2_layer6.0_shrinking_final_pyro_cascades_simulation500.xyz
6.0 116.93697491227367 7.08210419147868

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
6 -201.762412 -199.161981  2.600431       6.0      116.936975        7.082104

25 / 160 file name: bonds_angl_data_h2_layer122.0_shrinking_final_pyro_cascades_simulation500.xyz
122.0 114.35826035284427 9.970623342763238

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
122  99.887613  102.488044  2.600431     122.0       114.35826        9.970623

26 / 160 file name: bonds_angl_data_h2_layer78.0_shrinking_final_pyro_cascades_simulation500.xyz
78.0 117.14907071070787 6.8299201644966665

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
78 -14.531362 -11.930931  2.600431      78.0      117.149071         6.82992

27 / 160 file name: bonds_angl_data_h2_layer43.0_shrinking_final_pyro_cascades_simulation500.xyz
43.0 117.25178121705092 6.649576069878838

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
43 -105.546456 -102.946025  2.600431      43.0      117.251781        6.649576

28 / 160 file name: bonds_angl_data_h2_layer123.0_shrinking_final_pyro_cascades_simulation500.xyz
123.0 114.37989000494733 9.899201729652935

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
123,102.488044,105.088475,2.600431,123.0,114.37989,9.899202

29 / 160 file name: bonds_angl_data_h2_layer111.0_shrinking_final_pyro_cascades_simulation500.xyz
111.0 115.22892878514627 9.212155965526076

     beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
111  71.282869  73.8833  2.600431     111.0      115.228929        9.212156

30 / 160 file name: bonds_angl_data_h2_layer36.0_shrinking_final_pyro_cascades_simulation500.xyz
36.0 117.2668050619812 6.661347972319004

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
36 -123.749475 -121.149044  2.600431      36.0      117.266805        6.661348

31 / 160 file name: bonds_angl_data_h2_layer74.0_shrinking_final_pyro_cascades_simulation500.xyz
74.0 117.32178681318165 6.57642366753054

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
74 -24.933087 -22.332656  2.600431      74.0      117.321787        6.576424

32 / 160 file name: bonds_angl_data_h2_layer158.0_shrinking_final_pyro_cascades_simulation500.xyz
158.0 99.06179794156105 34.07892042969729

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
158,193.503138,196.103569,2.600431,158.0,99.061798,34.07892

33 / 160 file name: bonds_angl_data_h2_layer73.0_shrinking_final_pyro_cascades_simulation500.xyz
73.0 117.31449303944996 6.5576306812117435

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
73 -27.533519 -24.933087  2.600431      73.0      117.314493        6.557631

34 / 160 file name: bonds_angl_data_h2_layer60.0_shrinking_final_pyro_cascades_simulation500.xyz
60.0 117.43598759898421 6.394300795081258

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
60 -61.339125 -58.738694  2.600431      60.0      117.435988        6.394301

35 / 160 file name: bonds_angl_data_h2_layer32.0_shrinking_final_pyro_cascades_simulation500.xyz
32.0 117.39345213496068 6.448681782707632

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
32  -134.1512 -131.550769  2.600431      32.0      117.393452        6.448682

36 / 160 file name: bonds_angl_data_h2_layer51.0_shrinking_final_pyro_cascades_simulation500.xyz
51.0 117.33066364167013 6.538865855931378

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
51 -84.743006 -82.142575  2.600431      51.0      117.330664        6.538866

37 / 160 file name: bonds_angl_data_h2_layer28.0_shrinking_final_pyro_cascades_simulation500.xyz
28.0 117.24764070774752 6.680063107853747

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
28 -144.552925 -141.952494  2.600431      28.0      117.247641        6.680063

38 / 160 file name: bonds_angl_data_h2_layer40.0_shrinking_final_pyro_cascades_simulation500.xyz
40.0 117.34570356095549 6.452892864185477

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
40 -113.34775 -110.747319  2.600431      40.0      117.345704        6.452893

39 / 160 file name: bonds_angl_data_h2_layer18.0_shrinking_final_pyro_cascades_simulation500.xyz
18.0 117.16839212205164 6.873630389052122

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
18 -170.557237 -167.956806  2.600431      18.0      117.168392         6.87363

40 / 160 file name: bonds_angl_data_h2_layer62.0_shrinking_final_pyro_cascades_simulation500.xyz
62.0 117.41919842729604 6.350074919076671

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
62 -56.138262 -53.537831  2.600431      62.0      117.419198        6.350075

41 / 160 file name: bonds_angl_data_h2_layer26.0_shrinking_final_pyro_cascades_simulation500.xyz
26.0 117.23924846989225 6.652659600494057

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
26 -149.753787 -147.153356  2.600431      26.0      117.239248         6.65266

42 / 160 file name: bonds_angl_data_h2_layer72.0_shrinking_final_pyro_cascades_simulation500.xyz
72.0 117.33989048308969 6.535071466379932

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
72  -30.13395 -27.533519  2.600431      72.0       117.33989        6.535071

43 / 160 file name: bonds_angl_data_h2_layer54.0_shrinking_final_pyro_cascades_simulation500.xyz
54.0 117.28355045447191 6.534895255459395

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
54 -76.941712 -74.341281  2.600431      54.0       117.28355        6.534895

44 / 160 file name: bonds_angl_data_h2_layer147.0_shrinking_final_pyro_cascades_simulation500.xyz
147.0 114.49276908396644 9.916551840482292

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
147,164.898394,167.498825,2.600431,147.0,114.492769,9.916552

45 / 160 file name: bonds_angl_data_h2_layer38.0_shrinking_final_pyro_cascades_simulation500.xyz
38.0 117.42385559686784 6.3398433088317665

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
38 -118.548612 -115.948181  2.600431      38.0      117.423856        6.339843

46 / 160 file name: bonds_angl_data_h2_layer16.0_shrinking_final_pyro_cascades_simulation500.xyz
16.0 117.04425325469293 6.961013656716745

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
16  -175.7581 -173.157669  2.600431      16.0      117.044253        6.961014

47 / 160 file name: bonds_angl_data_h2_layer39.0_shrinking_final_pyro_cascades_simulation500.xyz
39.0 117.35047454119383 6.481076027742516

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
39 -115.948181 -113.34775  2.600431      39.0      117.350475        6.481076

48 / 160 file name: bonds_angl_data_h2_layer92.0_shrinking_final_pyro_cascades_simulation500.xyz
92.0 116.64871135922054 7.67132227476035

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
92  21.874675  24.475106  2.600431      92.0      116.648711        7.671322

49 / 160 file name: bonds_angl_data_h2_layer143.0_shrinking_final_pyro_cascades_simulation500.xyz
143.0 114.92518532639895 9.508973144427793

      beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
143  154.496669  157.0971  2.600431     143.0      114.925185        9.508973

50 / 160 file name: bonds_angl_data_h2_layer118.0_shrinking_final_pyro_cascades_simulation500.xyz
118.0 115.12170416517392 9.292413300932223

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
118  89.485888  92.086319  2.600431     118.0      115.121704        9.292413

51 / 160 file name: bonds_angl_data_h2_layer81.0_shrinking_final_pyro_cascades_simulation500.xyz
81.0 116.95097370613395 7.132504264354289

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
81  -6.730069 -4.129637  2.600431      81.0      116.950974        7.132504

52 / 160 file name: bonds_angl_data_h2_layer140.0_shrinking_final_pyro_cascades_simulation500.xyz
140.0 114.33109414477894 10.011080940716091

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
140,146.695375,149.295806,2.600431,140.0,114.331094,10.011081

53 / 160 file name: bonds_angl_data_h2_layer4.0_shrinking_final_pyro_cascades_simulation500.xyz
4.0 116.84296122288657 7.311132819511479

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
4 -206.963275 -204.362844  2.600431       4.0      116.842961        7.311133

54 / 160 file name: bonds_angl_data_h2_layer23.0_shrinking_final_pyro_cascades_simulation500.xyz
23.0 117.0882051439704 6.883503361920783

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
23 -157.555081 -154.95465  2.600431      23.0      117.088205        6.883503

55 / 160 file name: bonds_angl_data_h2_layer107.0_shrinking_final_pyro_cascades_simulation500.xyz
107.0 114.57278063228691 9.712544346884075

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
107  60.881144  63.481575  2.600431     107.0      114.572781        9.712544

56 / 160 file name: bonds_angl_data_h2_layer97.0_shrinking_final_pyro_cascades_simulation500.xyz
97.0 114.59776312760424 9.720202341265278

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
97  34.876831  37.477263  2.600431      97.0      114.597763        9.720202

57 / 160 file name: bonds_angl_data_h2_layer98.0_shrinking_final_pyro_cascades_simulation500.xyz
98.0 114.6713793793444 9.62253609718622

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
98  37.477263  40.077694  2.600431      98.0      114.671379        9.622536

58 / 160 file name: bonds_angl_data_h2_layer83.0_shrinking_final_pyro_cascades_simulation500.xyz
83.0 116.88739584848882 7.284401215932191

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
83  -1.529206  1.071225  2.600431      83.0      116.887396        7.284401

59 / 160 file name: bonds_angl_data_h2_layer24.0_shrinking_final_pyro_cascades_simulation500.xyz
24.0 117.18902093686118 6.778223883095663

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
24 -154.95465 -152.354219  2.600431      24.0      117.189021        6.778224

60 / 160 file name: bonds_angl_data_h2_layer87.0_shrinking_final_pyro_cascades_simulation500.xyz
87.0 116.75580581163828 7.419804965252863

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
87   8.872519  11.47295  2.600431      87.0      116.755806        7.419805

61 / 160 file name: bonds_angl_data_h2_layer42.0_shrinking_final_pyro_cascades_simulation500.xyz
42.0 117.33529610451922 6.472056891242173

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
42 -108.146887 -105.546456  2.600431      42.0      117.335296        6.472057

62 / 160 file name: bonds_angl_data_h2_layer61.0_shrinking_final_pyro_cascades_simulation500.xyz
61.0 117.45163476291258 6.324662041875646

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
61 -58.738694 -56.138262  2.600431      61.0      117.451635        6.324662

63 / 160 file name: bonds_angl_data_h2_layer132.0_shrinking_final_pyro_cascades_simulation500.xyz
132.0 114.72218815753449 9.546352921276567

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
132,125.891925,128.492356,2.600431,132.0,114.722188,9.546353

64 / 160 file name: bonds_angl_data_h2_layer106.0_shrinking_final_pyro_cascades_simulation500.xyz
106.0 114.53682567513538 9.816411856649923

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
106  58.280713  60.881144  2.600431     106.0      114.536826        9.816412

65 / 160 file name: bonds_angl_data_h2_layer57.0_shrinking_final_pyro_cascades_simulation500.xyz
57.0 117.36435681900112 6.467607001208849

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
57 -69.140419 -66.539987  2.600431      57.0      117.364357        6.467607

66 / 160 file name: bonds_angl_data_h2_layer5.0_shrinking_final_pyro_cascades_simulation500.xyz
5.0 116.88232645485695 7.162530857684105

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
5 -204.362844 -201.762412  2.600431       5.0      116.882326        7.162531

67 / 160 file name: bonds_angl_data_h2_layer27.0_shrinking_final_pyro_cascades_simulation500.xyz
27.0 117.22047157749338 6.672217931035416

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
27 -147.153356 -144.552925  2.600431      27.0      117.220472        6.672218

68 / 160 file name: bonds_angl_data_h2_layer11.0_shrinking_final_pyro_cascades_simulation500.xyz
11.0 117.03781734926214 7.011147042919464

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
11 -188.760256 -186.159825  2.600431      11.0      117.037817        7.011147

69 / 160 file name: bonds_angl_data_h2_layer58.0_shrinking_final_pyro_cascades_simulation500.xyz
58.0 117.42898475896314 6.314190854887181

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
58 -66.539987 -63.939556  2.600431      58.0      117.428985        6.314191

70 / 160 file name: bonds_angl_data_h2_layer100.0_shrinking_final_pyro_cascades_simulation500.xyz
100.0 115.2006358803101 9.087836734485299

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
100  42.678125  45.278556  2.600431     100.0      115.200636        9.087837

71 / 160 file name: bonds_angl_data_h2_layer76.0_shrinking_final_pyro_cascades_simulation500.xyz
76.0 117.20317615498954 6.728256593527326

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
76 -19.732225 -17.131794  2.600431      76.0      117.203176        6.728257

72 / 160 file name: bonds_angl_data_h2_layer20.0_shrinking_final_pyro_cascades_simulation500.xyz
20.0 117.08314785509893 6.968593427077227

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
20 -165.356375 -162.755944  2.600431      20.0      117.083148        6.968593

73 / 160 file name: bonds_angl_data_h2_layer67.0_shrinking_final_pyro_cascades_simulation500.xyz
67.0 117.42271306297629 6.477196094192282

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
67 -43.136106 -40.535675  2.600431      67.0      117.422713        6.477196

74 / 160 file name: bonds_angl_data_h2_layer66.0_shrinking_final_pyro_cascades_simulation500.xyz
66.0 117.47009280792587 6.354445396203662

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
66 -45.736537 -43.136106  2.600431      66.0      117.470093        6.354445

75 / 160 file name: bonds_angl_data_h2_layer110.0_shrinking_final_pyro_cascades_simulation500.xyz
110.0 115.36158937331484 9.025714415488439

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
110  68.682438  71.282869  2.600431     110.0      115.361589        9.025714

76 / 160 file name: bonds_angl_data_h2_layer19.0_shrinking_final_pyro_cascades_simulation500.xyz
19.0 117.1186792121806 6.872003261627619

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
19 -167.956806 -165.356375  2.600431      19.0      117.118679        6.872003

77 / 160 file name: bonds_angl_data_h2_layer50.0_shrinking_final_pyro_cascades_simulation500.xyz
50.0 117.31423075497023 6.475324820044233

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
50 -87.343437 -84.743006  2.600431      50.0      117.314231        6.475325

78 / 160 file name: bonds_angl_data_h2_layer113.0_shrinking_final_pyro_cascades_simulation500.xyz
113.0 114.69786892101247 9.658268340185579

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
113  76.483731  79.084163  2.600431     113.0      114.697869        9.658268

79 / 160 file name: bonds_angl_data_h2_layer75.0_shrinking_final_pyro_cascades_simulation500.xyz
75.0 117.20919707563802 6.797599116470395

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
75 -22.332656 -19.732225  2.600431      75.0      117.209197        6.797599

80 / 160 file name: bonds_angl_data_h2_layer80.0_shrinking_final_pyro_cascades_simulation500.xyz
80.0 117.05912755736338 6.9485381583833306

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
80    -9.3305 -6.730069  2.600431      80.0      117.059128        6.948538

81 / 160 file name: bonds_angl_data_h2_layer84.0_shrinking_final_pyro_cascades_simulation500.xyz
84.0 116.86658904532966 7.277207338507115

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
84   1.071225  3.671656  2.600431      84.0      116.866589        7.277207

82 / 160 file name: bonds_angl_data_h2_layer120.0_shrinking_final_pyro_cascades_simulation500.xyz
120.0 115.07427627395927 9.351824540473073

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
120   94.68675  97.287181  2.600431     120.0      115.074276        9.351825

83 / 160 file name: bonds_angl_data_h2_layer141.0_shrinking_final_pyro_cascades_simulation500.xyz
141.0 114.49241467564688 9.785463348669838

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
141,149.295806,151.896238,2.600431,141.0,114.492415,9.785463

84 / 160 file name: bonds_angl_data_h2_layer3.0_shrinking_final_pyro_cascades_simulation500.xyz
3.0 116.86124222828532 7.260743053323998

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
3 -209.563706 -206.963275  2.600431       3.0      116.861242        7.260743

85 / 160 file name: bonds_angl_data_h2_layer64.0_shrinking_final_pyro_cascades_simulation500.xyz
64.0 117.43856626550681 6.3843214896474745

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
64   -50.9374 -48.336969  2.600431      64.0      117.438566        6.384321

86 / 160 file name: bonds_angl_data_h2_layer8.0_shrinking_final_pyro_cascades_simulation500.xyz
8.0 116.95682798960573 7.1171444301532425

   beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
8 -196.56155 -193.961119  2.600431       8.0      116.956828        7.117144

87 / 160 file name: bonds_angl_data_h2_layer119.0_shrinking_final_pyro_cascades_simulation500.xyz
119.0 115.18655285407158 9.19643073452375

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
119  92.086319  94.68675  2.600431     119.0      115.186553        9.196431

88 / 160 file name: bonds_angl_data_h2_layer59.0_shrinking_final_pyro_cascades_simulation500.xyz
59.0 117.41331425291139 6.306716639906136

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
59 -63.939556 -61.339125  2.600431      59.0      117.413314        6.306717

89 / 160 file name: bonds_angl_data_h2_layer103.0_shrinking_final_pyro_cascades_simulation500.xyz
103.0 115.05942628587074 9.260149990799526

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
103  50.479419  53.07985  2.600431     103.0      115.059426         9.26015

90 / 160 file name: bonds_angl_data_h2_layer88.0_shrinking_final_pyro_cascades_simulation500.xyz
88.0 116.69669829793149 7.51445506162776

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
88   11.47295  14.073381  2.600431      88.0      116.696698        7.514455

91 / 160 file name: bonds_angl_data_h2_layer108.0_shrinking_final_pyro_cascades_simulation500.xyz
108.0 114.87756022365262 9.547105769716643

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
108  63.481575  66.082006  2.600431     108.0       114.87756        9.547106

92 / 160 file name: bonds_angl_data_h2_layer104.0_shrinking_final_pyro_cascades_simulation500.xyz
104.0 114.9314384195907 9.475326821370215

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
104   53.07985  55.680281  2.600431     104.0      114.931438        9.475327

93 / 160 file name: bonds_angl_data_h2_layer21.0_shrinking_final_pyro_cascades_simulation500.xyz
21.0 117.14683984261136 6.808835045881642

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
21 -162.755944 -160.155512  2.600431      21.0       117.14684        6.808835

94 / 160 file name: bonds_angl_data_h2_layer99.0_shrinking_final_pyro_cascades_simulation500.xyz
99.0 115.05915468444238 9.325339999154163

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
99  40.077694  42.678125  2.600431      99.0      115.059155         9.32534

95 / 160 file name: bonds_angl_data_h2_layer47.0_shrinking_final_pyro_cascades_simulation500.xyz
47.0 117.30917619888169 6.521744678987626

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
47 -95.144731 -92.5443  2.600431      47.0      117.309176        6.521745

96 / 160 file name: bonds_angl_data_h2_layer126.0_shrinking_final_pyro_cascades_simulation500.xyz
126.0 115.07495747472716 9.22711189901103

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
126,110.289338,112.889769,2.600431,126.0,115.074957,9.227112

97 / 160 file name: bonds_angl_data_h2_layer71.0_shrinking_final_pyro_cascades_simulation500.xyz
71.0 117.38023749765843 6.54674062157105

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
71 -32.734381 -30.13395  2.600431      71.0      117.380237        6.546741

98 / 160 file name: bonds_angl_data_h2_layer89.0_shrinking_final_pyro_cascades_simulation500.xyz
89.0 116.6619288660008 7.610119939161129

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
89  14.073381  16.673813  2.600431      89.0      116.661929         7.61012

99 / 160 file name: bonds_angl_data_h2_layer144.0_shrinking_final_pyro_cascades_simulation500.xyz
144.0 115.16334328031843 9.230090824942694

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
144   157.0971  159.697531  2.600431     144.0      115.163343        9.230091

100 / 160 file name: bonds_angl_data_h2_layer138.0_shrinking_final_pyro_cascades_simulation500.xyz
138.0 114.88480071926543 9.536210036508683

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
138,141.494513,144.094944,2.600431,138.0,114.884801,9.53621

101 / 160 file name: bonds_angl_data_h2_layer49.0_shrinking_final_pyro_cascades_simulation500.xyz
49.0 117.19546974386817 6.757800879333307

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
49 -89.943869 -87.343437  2.600431      49.0       117.19547        6.757801

102 / 160 file name: bonds_angl_data_h2_layer136.0_shrinking_final_pyro_cascades_simulation500.xyz
136.0 115.12955989427736 9.273752005761937

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
136  136.29365  138.894081  2.600431     136.0       115.12956        9.273752

103 / 160 file name: bonds_angl_data_h2_layer159.0_shrinking_final_pyro_cascades_simulation500.xyz
159.0 97.43218571981207 34.84992744154214

      beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
159  196.103569  198.704  2.600431     159.0       97.432186       34.849927

104 / 160 file name: bonds_angl_data_h2_layer133.0_shrinking_final_pyro_cascades_simulation500.xyz
133.0 114.90457634939054 9.378632457738506

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
133,128.492356,131.092788,2.600431,133.0,114.904576,9.378632

105 / 160 file name: bonds_angl_data_h2_layer52.0_shrinking_final_pyro_cascades_simulation500.xyz
52.0 117.29323722958038 6.654935774542037

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
52 -82.142575 -79.542144  2.600431      52.0      117.293237        6.654936

106 / 160 file name: bonds_angl_data_h2_layer65.0_shrinking_final_pyro_cascades_simulation500.xyz
65.0 117.44861247787647 6.306452252442698

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
65 -48.336969 -45.736537  2.600431      65.0      117.448612        6.306452

107 / 160 file name: bonds_angl_data_h2_layer130.0_shrinking_final_pyro_cascades_simulation500.xyz
130.0 114.77176658166209 9.676850566822422

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
130,120.691063,123.291494,2.600431,130.0,114.771767,9.676851

108 / 160 file name: bonds_angl_data_h2_layer37.0_shrinking_final_pyro_cascades_simulation500.xyz
37.0 117.31463830461801 6.548121034491931

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
37 -121.149044 -118.548612  2.600431      37.0      117.314638        6.548121

109 / 160 file name: bonds_angl_data_h2_layer128.0_shrinking_final_pyro_cascades_simulation500.xyz
128.0 115.21923918935808 9.185432103703244

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
128   115.4902  118.090631  2.600431     128.0      115.219239        9.185432

110 / 160 file name: bonds_angl_data_h2_layer112.0_shrinking_final_pyro_cascades_simulation500.xyz
112.0 115.0336142329345 9.325401140844804

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
112    73.8833  76.483731  2.600431     112.0      115.033614        9.325401

111 / 160 file name: bonds_angl_data_h2_layer77.0_shrinking_final_pyro_cascades_simulation500.xyz
77.0 117.22919089294173 6.731783280855677

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
77 -17.131794 -14.531362  2.600431      77.0      117.229191        6.731783

112 / 160 file name: bonds_angl_data_h2_layer152.0_shrinking_final_pyro_cascades_simulation500.xyz
152.0 116.42284543766137 7.863697044769747

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
152  177.90055  180.500981  2.600431     152.0      116.422845        7.863697

113 / 160 file name: bonds_angl_data_h2_layer70.0_shrinking_final_pyro_cascades_simulation500.xyz
70.0 117.37580438148143 6.55875647622544

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
70 -35.334812 -32.734381  2.600431      70.0      117.375804        6.558756

114 / 160 file name: bonds_angl_data_h2_layer25.0_shrinking_final_pyro_cascades_simulation500.xyz
25.0 117.19164412701848 6.732723492372866

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
25 -152.354219 -149.753787  2.600431      25.0      117.191644        6.732723

115 / 160 file name: bonds_angl_data_h2_layer116.0_shrinking_final_pyro_cascades_simulation500.xyz
116.0 114.8055994688331 9.507418460779775

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
116  84.285025  86.885456  2.600431     116.0      114.805599        9.507418

116 / 160 file name: bonds_angl_data_h2_layer93.0_shrinking_final_pyro_cascades_simulation500.xyz
93.0 116.56263921192577 7.757178565386288

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
93  24.475106  27.075538  2.600431      93.0      116.562639        7.757179

117 / 160 file name: bonds_angl_data_h2_layer14.0_shrinking_final_pyro_cascades_simulation500.xyz
14.0 117.0071104480867 7.051186534481727

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
14 -180.958962 -178.358531  2.600431      14.0       117.00711        7.051187

118 / 160 file name: bonds_angl_data_h2_layer34.0_shrinking_final_pyro_cascades_simulation500.xyz
34.0 117.28595467440736 6.58142562911686

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
34 -128.950337 -126.349906  2.600431      34.0      117.285955        6.581426

119 / 160 file name: bonds_angl_data_h2_layer154.0_shrinking_final_pyro_cascades_simulation500.xyz
154.0 116.38419826056142 7.9520665717699615

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
154,183.101413,185.701844,2.600431,154.0,116.384198,7.952067

120 / 160 file name: bonds_angl_data_h2_layer68.0_shrinking_final_pyro_cascades_simulation500.xyz
68.0 117.41530490432628 6.350403357031305

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
68 -40.535675 -37.935244  2.600431      68.0      117.415305        6.350403

121 / 160 file name: bonds_angl_data_h2_layer125.0_shrinking_final_pyro_cascades_simulation500.xyz
125.0 114.86287303503708 9.555234265915054

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
125,107.688906,110.289338,2.600431,125.0,114.862873,9.555234

122 / 160 file name: bonds_angl_data_h2_layer153.0_shrinking_final_pyro_cascades_simulation500.xyz
153.0 116.3885784561109 8.023829157050017

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
153,180.500981,183.101413,2.600431,153.0,116.388578,8.023829

123 / 160 file name: bonds_angl_data_h2_layer55.0_shrinking_final_pyro_cascades_simulation500.xyz
55.0 117.3002023859122 6.597060419413869

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
55 -74.341281 -71.74085  2.600431      55.0      117.300202         6.59706

124 / 160 file name: bonds_angl_data_h2_layer114.0_shrinking_final_pyro_cascades_simulation500.xyz
114.0 114.47724325262935 9.893647672268477

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
114  79.084163  81.684594  2.600431     114.0      114.477243        9.893648

125 / 160 file name: bonds_angl_data_h2_layer129.0_shrinking_final_pyro_cascades_simulation500.xyz
129.0 115.03107728606062 9.347313914523339

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
129,118.090631,120.691063,2.600431,129.0,115.031077,9.347314

126 / 160 file name: bonds_angl_data_h2_layer15.0_shrinking_final_pyro_cascades_simulation500.xyz
15.0 117.0324947218731 6.993000526277086

     beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
15 -178.358531 -175.7581  2.600431      15.0      117.032495        6.993001

127 / 160 file name: bonds_angl_data_h2_layer22.0_shrinking_final_pyro_cascades_simulation500.xyz
22.0 117.09035052759516 6.825213933336331

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
22 -160.155512 -157.555081  2.600431      22.0      117.090351        6.825214

128 / 160 file name: bonds_angl_data_h2_layer9.0_shrinking_final_pyro_cascades_simulation500.xyz
9.0 116.9790855504679 7.080059764810736

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
9 -193.961119 -191.360687  2.600431       9.0      116.979086         7.08006

129 / 160 file name: bonds_angl_data_h2_layer79.0_shrinking_final_pyro_cascades_simulation500.xyz
79.0 117.05546477349496 6.9530535692438225

    beginning  ending    height  z_layers  mean_bond_angl  disp_bond_angl
79 -11.930931 -9.3305  2.600431      79.0      117.055465        6.953054

130 / 160 file name: bonds_angl_data_h2_layer85.0_shrinking_final_pyro_cascades_simulation500.xyz
85.0 116.81629734046425 7.335708969540622

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
85   3.671656  6.272088  2.600431      85.0      116.816297        7.335709

131 / 160 file name: bonds_angl_data_h2_layer150.0_shrinking_final_pyro_cascades_simulation500.xyz
150.0 116.11238837776054 8.281340715586847

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
150,172.699688,175.300119,2.600431,150.0,116.112388,8.281341

132 / 160 file name: bonds_angl_data_h2_layer109.0_shrinking_final_pyro_cascades_simulation500.xyz
109.0 115.19833189076734 9.089831328707776

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
109  66.082006  68.682438  2.600431     109.0      115.198332        9.089831

133 / 160 file name: bonds_angl_data_h2_layer121.0_shrinking_final_pyro_cascades_simulation500.xyz
121.0 114.75504917655824 9.668307404314522

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
121  97.287181  99.887613  2.600431     121.0      114.755049        9.668307

134 / 160 file name: bonds_angl_data_h2_layer146.0_shrinking_final_pyro_cascades_simulation500.xyz
146.0 114.75387571831165 9.742236187579675

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
146,162.297963,164.898394,2.600431,146.0,114.753876,9.742236

135 / 160 file name: bonds_angl_data_h2_layer137.0_shrinking_final_pyro_cascades_simulation500.xyz
137.0 115.05696537496844 9.341571759996468

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
137,138.894081,141.494513,2.600431,137.0,115.056965,9.341572

136 / 160 file name: bonds_angl_data_h2_layer124.0_shrinking_final_pyro_cascades_simulation500.xyz
124.0 114.54497282953027 9.793132958126229

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
124,105.088475,107.688906,2.600431,124.0,114.544973,9.793133

137 / 160 file name: bonds_angl_data_h2_layer94.0_shrinking_final_pyro_cascades_simulation500.xyz
94.0 116.51884788208784 7.850233011777554

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
94  27.075538  29.675969  2.600431      94.0      116.518848        7.850233

138 / 160 file name: bonds_angl_data_h2_layer35.0_shrinking_final_pyro_cascades_simulation500.xyz
35.0 117.30187954104666 6.632658221471028

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
35 -126.349906 -123.749475  2.600431      35.0       117.30188        6.632658

139 / 160 file name: bonds_angl_data_h2_layer1.0_shrinking_final_pyro_cascades_simulation500.xyz
1.0 116.75358780194104 7.38626618777814

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
1 -214.764569 -212.164137  2.600431       1.0      116.753588        7.386266

140 / 160 file name: bonds_angl_data_h2_layer134.0_shrinking_final_pyro_cascades_simulation500.xyz
134.0 115.18981263550931 9.13072741284356

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
134,131.092788,133.693219,2.600431,134.0,115.189813,9.130727

141 / 160 file name: bonds_angl_data_h2_layer0.0_shrinking_final_pyro_cascades_simulation500.xyz
0.0 116.89078855669541 7.244506836040153

   beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
0   -217.365 -214.764569  2.600431       0.0      116.890789        7.244507

142 / 160 file name: bonds_angl_data_h2_layer53.0_shrinking_final_pyro_cascades_simulation500.xyz
53.0 117.25289319624079 6.639474481036269

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
53 -79.542144 -76.941712  2.600431      53.0      117.252893        6.639474

143 / 160 file name: bonds_angl_data_h2_layer29.0_shrinking_final_pyro_cascades_simulation500.xyz
29.0 117.2550420803801 6.6700215348158665

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
29 -141.952494 -139.352062  2.600431      29.0      117.255042        6.670022

144 / 160 file name: bonds_angl_data_h2_layer82.0_shrinking_final_pyro_cascades_simulation500.xyz
82.0 116.84869662583277 7.356823816657263

    beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
82  -4.129637 -1.529206  2.600431      82.0      116.848697        7.356824

145 / 160 file name: bonds_angl_data_h2_layer156.0_shrinking_final_pyro_cascades_simulation500.xyz
156.0 116.50109739835243 7.8104347897895625

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
156,188.302275,190.902706,2.600431,156.0,116.501097,7.810435

146 / 160 file name: bonds_angl_data_h2_layer127.0_shrinking_final_pyro_cascades_simulation500.xyz
127.0 115.2625114035406 9.060511958047707

      beginning    ending    height  z_layers  mean_bond_angl  disp_bond_angl
127  112.889769  115.4902  2.600431     127.0      115.262511        9.060512

147 / 160 file name: bonds_angl_data_h2_layer117.0_shrinking_final_pyro_cascades_simulation500.xyz
117.0 115.0055323153351 9.341666242149676

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
117  86.885456  89.485888  2.600431     117.0      115.005532        9.341666

148 / 160 file name: bonds_angl_data_h2_layer148.0_shrinking_final_pyro_cascades_simulation500.xyz
148.0 114.75892219113283 9.685527359166267

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
148,167.498825,170.099256,2.600431,148.0,114.758922,9.685527

149 / 160 file name: bonds_angl_data_h2_layer101.0_shrinking_final_pyro_cascades_simulation500.xyz
101.0 115.26153856638906 9.048146134741039

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
101  45.278556  47.878988  2.600431     101.0      115.261539        9.048146

150 / 160 file name: bonds_angl_data_h2_layer102.0_shrinking_final_pyro_cascades_simulation500.xyz
102.0 115.27631255312447 9.105239166322045

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
102  47.878988  50.479419  2.600431     102.0      115.276313        9.105239

151 / 160 file name: bonds_angl_data_h2_layer48.0_shrinking_final_pyro_cascades_simulation500.xyz
48.0 117.23352267881346 6.6140546419442465

    beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
48   -92.5443 -89.943869  2.600431      48.0      117.233523        6.614055

152 / 160 file name: bonds_angl_data_h2_layer12.0_shrinking_final_pyro_cascades_simulation500.xyz
12.0 116.97612236322963 7.051695272270735

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
12 -186.159825 -183.559394  2.600431      12.0      116.976122        7.051695

153 / 160 file name: bonds_angl_data_h2_layer95.0_shrinking_final_pyro_cascades_simulation500.xyz
95.0 116.35683539659256 8.112848944279165

    beginning   ending    height  z_layers  mean_bond_angl  disp_bond_angl
95  29.675969  32.2764  2.600431      95.0      116.356835        8.112849

154 / 160 file name: bonds_angl_data_h2_layer151.0_shrinking_final_pyro_cascades_simulation500.xyz
151.0 116.2990025444584 8.089222384098491

      beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
151  175.300119  177.90055  2.600431     151.0      116.299003        8.089222

155 / 160 file name: bonds_angl_data_h2_layer41.0_shrinking_final_pyro_cascades_simulation500.xyz
41.0 117.27947307479752 6.549078258351178

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
41 -110.747319 -108.146887  2.600431      41.0      117.279473        6.549078

156 / 160 file name: bonds_angl_data_h2_layer105.0_shrinking_final_pyro_cascades_simulation500.xyz
105.0 114.77728214156684 9.591540860510731

     beginning     ending    height  z_layers  mean_bond_angl  disp_bond_angl
105  55.680281  58.280713  2.600431     105.0      114.777282        9.591541

157 / 160 file name: bonds_angl_data_h2_layer17.0_shrinking_final_pyro_cascades_simulation500.xyz
17.0 117.11287867615141 6.880677432261414

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
17 -173.157669 -170.557237  2.600431      17.0      117.112879        6.880677

158 / 160 file name: bonds_angl_data_h2_layer33.0_shrinking_final_pyro_cascades_simulation500.xyz
33.0 117.40796375060886 6.408910629815823

     beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
33 -131.550769 -128.950337  2.600431      33.0      117.407964        6.408911

159 / 160 file name: bonds_angl_data_h2_layer155.0_shrinking_final_pyro_cascades_simulation500.xyz
155.0 116.48749716738394 7.8311377152361725

,beginning,ending,height,z_layers,mean_bond_angl,disp_bond_angl
155,185.701844,188.302275,2.600431,155.0,116.487497,7.831138

160 / 160 file name: bonds_angl_data_h2_layer2.0_shrinking_final_pyro_cascades_simulation500.xyz
2.0 116.73352586677156 7.4175100073113

    beginning      ending    height  z_layers  mean_bond_angl  disp_bond_angl
2 -212.164137 -209.563706  2.600431       2.0      116.733526         7.41751

Done